# Composing and Sending Messages

In this tutorial, we'll learn how to compose and send messages to a Cosmos blockchain using Telescope-generated types. Messages are the primary way to interact with a blockchain, instructing it to perform operations like transferring tokens, delegating stake, or submitting governance proposals.

## Understanding Blockchain Messages

In Cosmos SDK chains, all on-chain actions happen through messages. Think of these messages as instructions that tell the blockchain what you want to do. When these messages are included in a transaction and that transaction is validated and executed, they change the state of the blockchain.

Telescope generates TypeScript types for these messages from the chain's Protocol Buffer definitions, making it easy to compose valid messages in a type-safe way.

## Basic Message Structure

Let's start with the most common message type: sending tokens from one address to another.

```typescript
import { MsgSend } from "./cosmos/bank/v1beta1/tx";

// Create a bank send message
const sendMsg = MsgSend.fromPartial({
  fromAddress: "cosmos1sender...",
  toAddress: "cosmos1recipient...",
  amount: [
    { denom: "uatom", amount: "1000000" } // 1 ATOM (in microatoms)
  ]
});
```

The structure of this message is simple:
- `fromAddress`: The sender's address
- `toAddress`: The recipient's address
- `amount`: An array of coins to send, each with a denomination and amount

Notice we're using the `fromPartial()` method. This is a helper method generated by Telescope that properly initializes the message with default values for any fields you omit.

## Creating Different Types of Messages

Let's look at how to create messages for some common operations:

### Delegating Stake

```typescript
import { MsgDelegate } from "./cosmos/staking/v1beta1/tx";

const delegateMsg = MsgDelegate.fromPartial({
  delegatorAddress: "cosmos1...",
  validatorAddress: "cosmosvaloper1...",
  amount: { denom: "uatom", amount: "5000000" } // 5 ATOM
});
```

### Voting on a Governance Proposal

```typescript
import { MsgVote, VoteOption } from "./cosmos/gov/v1beta1/tx";

const voteMsg = MsgVote.fromPartial({
  proposalId: 42, // The ID of the proposal
  voter: "cosmos1...",
  option: VoteOption.VOTE_OPTION_YES // Could also be NO, ABSTAIN, etc.
});
```

### Submitting a Governance Proposal

```typescript
import { MsgSubmitProposal } from "./cosmos/gov/v1beta1/tx";
import { TextProposal } from "./cosmos/gov/v1beta1/gov";
import { Any } from "./google/protobuf/any";

// First, create the proposal content
const textProposal = TextProposal.fromPartial({
  title: "My Awesome Proposal",
  description: "This proposal aims to improve the network by..."
});

// Pack it into an Any type
const packedProposal = Any.pack(textProposal, "/cosmos.gov.v1beta1.TextProposal");

// Now create the submit proposal message
const submitProposalMsg = MsgSubmitProposal.fromPartial({
  content: packedProposal,
  initialDeposit: [{ denom: "uatom", amount: "10000000" }], // 10 ATOM
  proposer: "cosmos1..."
});
```

## Using MessageComposer for Convenience

Telescope also generates a `MessageComposer` for each module, which provides a more convenient way to create messages:

```typescript
import { bankComposer } from "./cosmos/bank/v1beta1/tx.composer";
import { stakingComposer } from "./cosmos/staking/v1beta1/tx.composer";

// Same send message as before, but using the composer
const sendMsg = bankComposer.send({
  fromAddress: "cosmos1...",
  toAddress: "cosmos1...",
  amount: [{ denom: "uatom", amount: "1000000" }]
});

// Delegate message using the composer
const delegateMsg = stakingComposer.delegate({
  delegatorAddress: "cosmos1...",
  validatorAddress: "cosmosvaloper1...",
  amount: { denom: "uatom", amount: "5000000" }
});
```

The message composer automatically adds the correct type URL to each message, which is needed when sending the messages to the blockchain.

## Combining Multiple Messages in a Transaction

One powerful feature of Cosmos SDK chains is the ability to include multiple messages in a single transaction. This allows you to perform several operations atomically:

```typescript
// Create multiple messages
const messages = [
  bankComposer.send({
    fromAddress: "cosmos1...",
    toAddress: "cosmos1recipient1...",
    amount: [{ denom: "uatom", amount: "1000000" }]
  }),
  bankComposer.send({
    fromAddress: "cosmos1...",
    toAddress: "cosmos1recipient2...",
    amount: [{ denom: "uatom", amount: "2000000" }]
  }),
  stakingComposer.delegate({
    delegatorAddress: "cosmos1...",
    validatorAddress: "cosmosvaloper1...",
    amount: { denom: "uatom", amount: "5000000" }
  })
];

// These messages will be sent in a single transaction
```

## Sending Messages to the Blockchain

Now that you know how to compose messages, let's see how to send them to the blockchain.

### Using SigningStargateClient

The most common way to send transactions is using the `SigningStargateClient` from CosmJS:

```typescript
import { SigningStargateClient } from "@cosmjs/stargate";
import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
import { GasPrice } from "@cosmjs/stargate";
import { registry } from "./registry";

// First, set up a wallet (you would normally have a more secure way to handle the mnemonic)
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(
  "your mnemonic phrase here",
  { prefix: "cosmos" }
);
const [firstAccount] = await wallet.getAccounts();

// Create a signing client
const client = await SigningStargateClient.connectWithSigner(
  "https://rpc.cosmos.network", // Your RPC endpoint
  wallet,
  { 
    registry, // This is the registry from Telescope
    gasPrice: GasPrice.fromString("0.025uatom") 
  }
);

// Prepare your message
const sendMsg = {
  typeUrl: "/cosmos.bank.v1beta1.MsgSend",
  value: {
    fromAddress: firstAccount.address,
    toAddress: "cosmos1recipient...",
    amount: [{ denom: "uatom", amount: "1000000" }]
  }
};

// Send the transaction
try {
  const result = await client.signAndBroadcast(
    firstAccount.address,
    [sendMsg],
    {
      amount: [{ denom: "uatom", amount: "5000" }],
      gas: "200000"
    }
  );
  
  console.log("Transaction hash:", result.transactionHash);
  console.log("Transaction result:", result);
  
  if (result.code === 0) {
    console.log("Transaction successful!");
  } else {
    console.error("Transaction failed:", result.rawLog);
  }
} catch (error) {
  console.error("Error sending transaction:", error);
}
```

### Using the Telescope-generated TxClient

Telescope also generates a `createTxClient` function that makes it even easier to send transactions:

```typescript
import { createTxClient } from "./tx";
import { MsgSend } from "./cosmos/bank/v1beta1/tx";
import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";

// Set up a wallet
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(
  "your mnemonic phrase here",
  { prefix: "cosmos" }
);
const [firstAccount] = await wallet.getAccounts();

// Create a transaction client
const txClient = await createTxClient({
  signer: wallet,
  rpcEndpoint: "https://rpc.cosmos.network"
});

// Create a message
const sendMsg = MsgSend.fromPartial({
  fromAddress: firstAccount.address,
  toAddress: "cosmos1recipient...",
  amount: [{ denom: "uatom", amount: "1000000" }]
});

// Send the transaction
try {
  const result = await txClient.signAndBroadcast(
    firstAccount.address,
    [sendMsg],
    {
      amount: [{ denom: "uatom", amount: "5000" }],
      gas: "200000"
    }
  );
  
  console.log("Transaction successful:", result);
} catch (error) {
  console.error("Error sending transaction:", error);
}
```

## Working with Legacy Systems: Amino Encoding

Some wallets and older systems use Amino encoding instead of Protobuf. Telescope generates Amino converters that make it easy to support both formats:

```typescript
import { AminoTypes } from "@cosmjs/stargate";
import { aminoConverters } from "./amino/converters";

const aminoTypes = new AminoTypes(aminoConverters);

// Convert a Protobuf message to Amino format
const aminoMsg = aminoTypes.toAmino({
  typeUrl: "/cosmos.bank.v1beta1.MsgSend",
  value: sendMsg
});

console.log(aminoMsg);
// Output: 
// {
//   type: "cosmos-sdk/MsgSend",
//   value: {
//     from_address: "cosmos1...",
//     to_address: "cosmos1...",
//     amount: [{ denom: "uatom", amount: "1000000" }]
//   }
// }

// Convert back from Amino to Protobuf
const protoMsg = aminoTypes.fromAmino(aminoMsg);
```

## Handling Message Responses

After sending a transaction, you'll want to handle the response:

```typescript
try {
  const result = await txClient.signAndBroadcast(
    firstAccount.address,
    [sendMsg],
    fee
  );
  
  // Check if the transaction was successful
  if (result.code === 0) {
    console.log("Transaction successful!");
    
    // For specific message types, you might want to extract data
    // For example, if submitting a proposal, get the proposal ID:
    if (result.events) {
      const submitProposalEvent = result.events.find(event => 
        event.type === "submit_proposal"
      );
      
      if (submitProposalEvent) {
        const proposalIdAttr = submitProposalEvent.attributes.find(attr =>
          attr.key === "proposal_id"
        );
        
        if (proposalIdAttr) {
          console.log("Created proposal ID:", proposalIdAttr.value);
        }
      }
    }
  } else {
    console.error("Transaction failed:", result.rawLog);
  }
} catch (error) {
  console.error("Error sending transaction:", error);
}
```

## Best Practices

When composing and sending messages:

1. **Always use `fromPartial()`**: This ensures default values are properly set for omitted fields.

2. **Validate inputs**: Although Telescope types help with type safety, it's good practice to validate inputs before creating messages, especially when they come from user input.

3. **Handle errors gracefully**: Network issues, gas estimation errors, and other problems can occur when sending transactions.

4. **Monitor transaction status**: For important transactions, consider implementing tracking by transaction hash to confirm they were included in a block.

5. **Consider gas and fees**: Set appropriate gas limits and fees to ensure your transaction is processed promptly.

6. **Batch related operations**: When possible, group related operations into a single transaction using multiple messages.

7. **Test on testnets first**: Before sending transactions to mainnet, test your code on a testnet.

## Conclusion

You've now learned how to compose messages using Telescope-generated types and send them to a Cosmos blockchain. These skills form the foundation for building applications that interact with any Cosmos SDK blockchain.

In the next tutorial, you'll learn about [calculating transaction fees](./calculating-fees.md) to ensure your transactions are processed efficiently. 