# Working with LCD Client Classes

In this tutorial, we'll explore how to work with LCD Client Classes generated by Telescope. These classes provide an object-oriented approach to querying blockchain data, making your code more maintainable and extensible.

## Understanding LCD Client Classes

LCD Client Classes take the functionality of LCD Clients (covered in the [previous tutorial](./lcd-clients.md)) and wrap them in a class-based architecture. This approach has several advantages:

1. **Extensibility**: You can easily extend the classes to add custom methods
2. **Modularity**: Each module is represented by its own class
3. **Testability**: Classes are easier to mock and test
4. **Encapsulation**: Implementation details are hidden behind a clean interface

Let's dive in and see how to use these classes in your projects.

## Setting Up LCD Client Classes

First, you need to enable LCD Client Classes generation in your Telescope configuration:

```typescript
// In your Telescope configuration
import { TelescopeOptions } from "@cosmology/types";

const options: TelescopeOptions = {
  lcdClientClasses: {
    enabled: true
  }
  // Other options...
};

export default options;
```

After running Telescope with this configuration, it will generate client classes for all modules in your Protobuf definitions.

## Creating Your First Client Class

Let's start by creating a basic client class to query the Cosmos Hub:

```typescript
import { createLCDClientClasses } from "./codegen/client-classes";

async function main() {
  // Create the client classes
  const clients = createLCDClientClasses({
    restEndpoint: "https://rest.cosmos.network"
  });
  
  console.log("Client classes created successfully!");
  
  // Access a specific module client
  const bankClient = clients.cosmos.bank.v1beta1;
  
  // Query an account's balance
  const address = "cosmos1..."; // Replace with a real address
  const { balances } = await bankClient.allBalances({ address });
  
  console.log(`Account ${address} has:`);
  balances.forEach(coin => {
    console.log(`- ${coin.amount} ${coin.denom}`);
  });
}

main().catch(console.error);
```

## Exploring Module Structure

Let's look closer at how these client classes are structured:

```typescript
// The client classes follow a nested structure similar to the protobuf packages
const clients = createLCDClientClasses({
  restEndpoint: "https://rest.cosmos.network"
});

// Each module has its own client class
const bankClient = clients.cosmos.bank.v1beta1;
const stakingClient = clients.cosmos.staking.v1beta1;
const govClient = clients.cosmos.gov.v1beta1;

// These classes have methods corresponding to the REST endpoints
async function exploreModules() {
  // Bank module methods
  console.log("Bank module methods:");
  console.log(Object.getOwnPropertyNames(
    Object.getPrototypeOf(bankClient)
  ).filter(name => name !== 'constructor'));
  
  // Staking module methods
  console.log("\nStaking module methods:");
  console.log(Object.getOwnPropertyNames(
    Object.getPrototypeOf(stakingClient)
  ).filter(name => name !== 'constructor'));
  
  // Gov module methods
  console.log("\nGov module methods:");
  console.log(Object.getOwnPropertyNames(
    Object.getPrototypeOf(govClient)
  ).filter(name => name !== 'constructor'));
}
```

## Extending Client Classes

One of the main advantages of using client classes is the ability to extend them with custom methods. Let's create an extended bank client with helpful utility methods:

```typescript
import { BankQueryClient } from "./codegen/cosmos/bank/v1beta1/query.lcd";
import axios from "axios";

// Create a specialized bank client with extended functionality
class EnhancedBankClient extends BankQueryClient {
  // Constructor stays the same
  constructor(axios, baseUrl) {
    super(axios, baseUrl);
  }
  
  // Add a method to get formatted token balance
  async getFormattedBalance(address, denom) {
    const response = await this.balance({
      address,
      denom
    });
    
    // Extract amount or default to zero
    const amount = response.balance?.amount || "0";
    
    // Format the amount based on token type
    if (denom.startsWith('u')) {
      // Convert micro units to standard units (divide by 1,000,000)
      const standardAmount = Number(amount) / 1_000_000;
      // Format with two decimal places
      const formattedAmount = standardAmount.toFixed(2);
      // Get the actual token symbol (remove the 'u' prefix)
      const symbol = denom.substring(1).toUpperCase();
      
      return `${formattedAmount} ${symbol}`;
    }
    
    // For other denominations, just return as is
    return `${amount} ${denom}`;
  }
  
  // Add a method to get all balances in a formatted way
  async getFormattedBalances(address) {
    const { balances } = await this.allBalances({ address });
    
    return balances.map(coin => {
      const { denom, amount } = coin;
      
      if (denom.startsWith('u')) {
        const standardAmount = Number(amount) / 1_000_000;
        const symbol = denom.substring(1).toUpperCase();
        return { denom: symbol, amount: standardAmount, formatted: `${standardAmount.toFixed(2)} ${symbol}` };
      }
      
      return { denom, amount: Number(amount), formatted: `${amount} ${denom}` };
    });
  }
  
  // Add a method to check if an account has sufficient balance
  async hasSufficientBalance(address, requiredAmount, denom) {
    const response = await this.balance({
      address,
      denom
    });
    
    const balance = response.balance?.amount || "0";
    return BigInt(balance) >= BigInt(requiredAmount);
  }
}

// Usage example
async function useEnhancedBankClient() {
  const baseUrl = "https://rest.cosmos.network";
  const axiosInstance = axios.create({ baseURL: baseUrl });
  
  // Create our enhanced client
  const bankClient = new EnhancedBankClient(axiosInstance, baseUrl);
  
  const address = "cosmos1..."; // Replace with a real address
  
  // Use the standard method
  const { balance } = await bankClient.balance({
    address,
    denom: "uatom"
  });
  console.log("Raw balance:", balance);
  
  // Use the enhanced methods
  const formattedBalance = await bankClient.getFormattedBalance(address, "uatom");
  console.log("Formatted balance:", formattedBalance);
  
  const allFormattedBalances = await bankClient.getFormattedBalances(address);
  console.log("All formatted balances:", allFormattedBalances);
  
  const hasSufficientFunds = await bankClient.hasSufficientBalance(address, "1000000", "uatom");
  console.log("Has at least 1 ATOM:", hasSufficientFunds);
}
```

## Creating a Composite Client

For applications that work with multiple modules, you can create a composite client that brings together functionality from different modules:

```typescript
import { BankQueryClient } from "./codegen/cosmos/bank/v1beta1/query.lcd";
import { StakingQueryClient } from "./codegen/cosmos/staking/v1beta1/query.lcd";
import { DistributionQueryClient } from "./codegen/cosmos/distribution/v1beta1/query.lcd";
import axios from "axios";

// Create a comprehensive account information client
class AccountInfoClient {
  private bankClient: BankQueryClient;
  private stakingClient: StakingQueryClient;
  private distributionClient: DistributionQueryClient;
  
  constructor(restEndpoint: string) {
    const axiosInstance = axios.create({ baseURL: restEndpoint });
    
    this.bankClient = new BankQueryClient(axiosInstance, restEndpoint);
    this.stakingClient = new StakingQueryClient(axiosInstance, restEndpoint);
    this.distributionClient = new DistributionQueryClient(axiosInstance, restEndpoint);
  }
  
  // Get comprehensive account overview
  async getAccountOverview(address: string) {
    // Execute all queries in parallel for efficiency
    const [
      balancesResponse,
      delegationsResponse,
      unbondingResponse,
      rewardsResponse
    ] = await Promise.all([
      this.bankClient.allBalances({ address }),
      this.stakingClient.delegatorDelegations({ delegatorAddr: address }),
      this.stakingClient.delegatorUnbondingDelegations({ delegatorAddr: address }),
      this.distributionClient.delegationTotalRewards({ delegatorAddress: address })
    ]);
    
    // Calculate total liquid balance
    const liquidBalance = balancesResponse.balances.reduce(
      (sum, coin) => sum + Number(coin.amount),
      0
    );
    
    // Calculate total staked balance
    const stakedBalance = delegationsResponse.delegationResponses.reduce(
      (sum, del) => sum + Number(del.balance.amount),
      0
    );
    
    // Calculate total unbonding balance
    const unbondingBalance = unbondingResponse.unbondingResponses.reduce(
      (sum, unbonding) => sum + unbonding.entries.reduce(
        (entrySum, entry) => entrySum + Number(entry.balance),
        0
      ),
      0
    );
    
    // Calculate total rewards
    const totalRewards = rewardsResponse.total.reduce(
      (sum, reward) => sum + Number(reward.amount),
      0
    );
    
    // Return combined information
    return {
      address,
      liquid: {
        balances: balancesResponse.balances,
        total: liquidBalance
      },
      staked: {
        delegations: delegationsResponse.delegationResponses,
        total: stakedBalance
      },
      unbonding: {
        entries: unbondingResponse.unbondingResponses,
        total: unbondingBalance
      },
      rewards: {
        details: rewardsResponse.rewards,
        total: totalRewards
      },
      netWorth: liquidBalance + stakedBalance + unbondingBalance + totalRewards
    };
  }
}

// Usage example
async function displayAccountOverview() {
  const client = new AccountInfoClient("https://rest.cosmos.network");
  
  const address = "cosmos1..."; // Replace with a real address
  const overview = await client.getAccountOverview(address);
  
  console.log(`Account Overview for ${address}:`);
  console.log(`Liquid Balance: ${overview.liquid.total / 1_000_000} ATOM`);
  console.log(`Staked Balance: ${overview.staked.total / 1_000_000} ATOM`);
  console.log(`Unbonding Balance: ${overview.unbonding.total / 1_000_000} ATOM`);
  console.log(`Pending Rewards: ${overview.rewards.total / 1_000_000} ATOM`);
  console.log(`Total Net Worth: ${overview.netWorth / 1_000_000} ATOM`);
  
  // If there are delegations, show the validators
  if (overview.staked.delegations.length > 0) {
    console.log("\nDelegations:");
    overview.staked.delegations.forEach(del => {
      console.log(`- ${del.delegation.validatorAddress}: ${Number(del.balance.amount) / 1_000_000} ATOM`);
    });
  }
}
```

## Adding Caching for Performance

For production applications, you might want to add caching to avoid unnecessary network requests:

```typescript
import { BankQueryClient } from "./codegen/cosmos/bank/v1beta1/query.lcd";

// Create a caching bank client
class CachingBankClient extends BankQueryClient {
  private cache = new Map();
  private cacheTTL = 30 * 1000; // 30 seconds cache time-to-live
  
  // Helper to generate cache keys
  private getCacheKey(method, params) {
    return `${method}:${JSON.stringify(params)}`;
  }
  
  // Override the balance method to add caching
  async balance(params) {
    const cacheKey = this.getCacheKey('balance', params);
    
    // Check if we have a cached response that's still valid
    const cachedItem = this.cache.get(cacheKey);
    if (cachedItem && Date.now() - cachedItem.timestamp < this.cacheTTL) {
      console.log(`Cache hit for ${cacheKey}`);
      return cachedItem.data;
    }
    
    // No cache hit, call the actual method
    console.log(`Cache miss for ${cacheKey}, fetching data...`);
    const response = await super.balance(params);
    
    // Cache the response
    this.cache.set(cacheKey, {
      data: response,
      timestamp: Date.now()
    });
    
    return response;
  }
  
  // Similarly override other methods you want to cache
  async allBalances(params) {
    const cacheKey = this.getCacheKey('allBalances', params);
    
    const cachedItem = this.cache.get(cacheKey);
    if (cachedItem && Date.now() - cachedItem.timestamp < this.cacheTTL) {
      console.log(`Cache hit for ${cacheKey}`);
      return cachedItem.data;
    }
    
    console.log(`Cache miss for ${cacheKey}, fetching data...`);
    const response = await super.allBalances(params);
    
    this.cache.set(cacheKey, {
      data: response,
      timestamp: Date.now()
    });
    
    return response;
  }
  
  // Method to clear the cache
  clearCache() {
    this.cache.clear();
    console.log("Cache cleared");
  }
  
  // Method to set custom TTL
  setCacheTTL(milliseconds) {
    this.cacheTTL = milliseconds;
    console.log(`Cache TTL set to ${milliseconds}ms`);
  }
}

// Example of using the caching client
async function demonstrateCaching() {
  const baseUrl = "https://rest.cosmos.network";
  const axiosInstance = axios.create({ baseURL: baseUrl });
  
  // Create caching client
  const bankClient = new CachingBankClient(axiosInstance, baseUrl);
  
  const address = "cosmos1..."; // Replace with a real address
  
  console.log("First request (will fetch from network):");
  await bankClient.balance({ address, denom: "uatom" });
  
  console.log("\nSecond request (should use cache):");
  await bankClient.balance({ address, denom: "uatom" });
  
  console.log("\nDifferent request (will fetch from network):");
  await bankClient.balance({ address, denom: "uosmo" });
  
  console.log("\nClearing cache...");
  bankClient.clearCache();
  
  console.log("\nRequest after clearing cache (will fetch from network):");
  await bankClient.balance({ address, denom: "uatom" });
}
```

## Adding Error Handling and Retries

For more robust applications, you might want to add error handling and retry logic:

```typescript
import { StakingQueryClient } from "./codegen/cosmos/staking/v1beta1/query.lcd";

// Create a client with error handling and retries
class RobustStakingClient extends StakingQueryClient {
  private maxRetries = 3;
  private baseDelay = 1000; // 1 second initial delay
  
  // Helper method to handle retries
  private async withRetry(method, params) {
    let lastError;
    
    for (let attempt = 1; attempt <= this.maxRetries; attempt++) {
      try {
        // Call the parent method
        return await method.call(this, params);
      } catch (error) {
        lastError = error;
        
        // Check if we should retry based on the error
        if (this.isRetryableError(error) && attempt < this.maxRetries) {
          const delay = this.calculateBackoff(attempt);
          console.warn(`Request failed (attempt ${attempt}/${this.maxRetries}). Retrying in ${delay}ms...`);
          await new Promise(resolve => setTimeout(resolve, delay));
        } else {
          // We've exhausted retries or it's not a retryable error
          throw error;
        }
      }
    }
    
    throw lastError;
  }
  
  // Determine if an error should trigger a retry
  private isRetryableError(error) {
    // Network errors or server errors (5xx) are retryable
    return (
      !error.response || // Network error
      (error.response && error.response.status >= 500) // Server error
    );
  }
  
  // Calculate exponential backoff
  private calculateBackoff(attempt) {
    return this.baseDelay * Math.pow(2, attempt - 1);
  }
  
  // Override methods to add retry logic
  async validators(params) {
    return this.withRetry(super.validators, params);
  }
  
  async validator(params) {
    return this.withRetry(super.validator, params);
  }
  
  async delegatorDelegations(params) {
    return this.withRetry(super.delegatorDelegations, params);
  }
  
  // Override other methods similarly...
}

// Usage example
async function demonstrateRetries() {
  const baseUrl = "https://rest.cosmos.network";
  const axiosInstance = axios.create({ 
    baseURL: baseUrl,
    timeout: 3000 // Short timeout to demonstrate timeouts
  });
  
  const stakingClient = new RobustStakingClient(axiosInstance, baseUrl);
  
  try {
    const { validators } = await stakingClient.validators({});
    console.log(`Successfully retrieved ${validators.length} validators`);
  } catch (error) {
    console.error("All retries failed:", error.message);
  }
}
```

## Creating a Complete Dashboard App

Let's put everything together into a complete example – a dashboard app that displays blockchain statistics:

```typescript
import axios from "axios";
import { 
  BankQueryClient, 
  StakingQueryClient, 
  GovQueryClient,
  MintQueryClient,
  TendermintQueryClient
} from "./codegen";

// Blockchain dashboard client with caching, retries, and error handling
class BlockchainDashboardClient {
  private bank: BankQueryClient;
  private staking: StakingQueryClient;
  private gov: GovQueryClient;
  private mint: MintQueryClient;
  private tendermint: TendermintQueryClient;
  
  private cache = new Map();
  private cacheTTL = 60 * 1000; // 1 minute
  
  constructor(restEndpoint: string) {
    const axiosInstance = axios.create({
      baseURL: restEndpoint,
      timeout: 10000
    });
    
    // Add response interceptor for error handling
    axiosInstance.interceptors.response.use(
      response => response,
      error => {
        console.error(`API Error: ${error.message}`);
        return Promise.reject(error);
      }
    );
    
    this.bank = new BankQueryClient(axiosInstance, restEndpoint);
    this.staking = new StakingQueryClient(axiosInstance, restEndpoint);
    this.gov = new GovQueryClient(axiosInstance, restEndpoint);
    this.mint = new MintQueryClient(axiosInstance, restEndpoint);
    this.tendermint = new TendermintQueryClient(axiosInstance, restEndpoint);
  }
  
  // Helper for caching
  private async getCachedData(key, fetcher) {
    const cachedItem = this.cache.get(key);
    if (cachedItem && Date.now() - cachedItem.timestamp < this.cacheTTL) {
      return cachedItem.data;
    }
    
    const data = await fetcher();
    this.cache.set(key, {
      data,
      timestamp: Date.now()
    });
    
    return data;
  }
  
  // Get blockchain overview
  async getDashboardData() {
    return this.getCachedData('dashboard', async () => {
      try {
        // Run all queries in parallel
        const [
          nodeInfo,
          latestBlock,
          validatorsResponse,
          activeProposalsResponse,
          supplyResponse,
          inflationResponse
        ] = await Promise.all([
          this.tendermint.getNodeInfo({}),
          this.tendermint.getLatestBlock({}),
          this.staking.validators({ status: "BOND_STATUS_BONDED" }),
          this.gov.proposals({ proposalStatus: 2 }), // PROPOSAL_STATUS_VOTING_PERIOD
          this.bank.totalSupply({}),
          this.mint.inflation({})
        ]);
        
        // Process the data
        const chainId = nodeInfo.defaultNodeInfo.network;
        const blockHeight = latestBlock.block.header.height;
        const blockTime = new Date(latestBlock.block.header.time);
        
        const activeValidators = validatorsResponse.validators;
        const totalVotingPower = activeValidators.reduce(
          (sum, v) => sum + BigInt(v.tokens),
          BigInt(0)
        );
        
        const topValidators = activeValidators
          .sort((a, b) => Number(BigInt(b.tokens) - BigInt(a.tokens)))
          .slice(0, 10)
          .map(v => ({
            name: v.description.moniker,
            address: v.operatorAddress,
            votingPower: Number(BigInt(v.tokens) * BigInt(100) / totalVotingPower),
            commission: parseFloat(v.commission.commissionRates.rate) * 100
          }));
        
        const activeProposals = activeProposalsResponse.proposals.map(p => ({
          id: p.proposalId,
          title: p.content.title,
          description: p.content.description,
          votingEndTime: p.votingEndTime
        }));
        
        const atomSupply = supplyResponse.supply.find(c => c.denom === "uatom");
        const totalAtoms = atomSupply 
          ? Number(atomSupply.amount) / 1_000_000 
          : 0;
        
        const inflation = parseFloat(inflationResponse.inflation) * 100;
        
        return {
          chainId,
          blockHeight,
          blockTime,
          validators: {
            active: activeValidators.length,
            top: topValidators
          },
          governance: {
            activeProposals
          },
          economics: {
            totalSupply: totalAtoms,
            inflation
          },
          lastUpdated: new Date()
        };
      } catch (error) {
        console.error("Error fetching dashboard data:", error);
        throw new Error(`Failed to fetch dashboard data: ${error.message}`);
      }
    });
  }
  
  // Clear the cache
  clearCache() {
    this.cache.clear();
  }
}

// Usage example
async function showDashboard() {
  const client = new BlockchainDashboardClient("https://rest.cosmos.network");
  
  try {
    const data = await client.getDashboardData();
    
    console.log(`=== ${data.chainId} Dashboard ===`);
    console.log(`Block Height: ${data.blockHeight}`);
    console.log(`Latest Block: ${data.blockTime}`);
    console.log(`Active Validators: ${data.validators.active}`);
    console.log(`Current Inflation: ${data.economics.inflation.toFixed(2)}%`);
    console.log(`Total ATOM Supply: ${data.economics.totalSupply.toLocaleString()} ATOM`);
    
    console.log("\nTop Validators:");
    data.validators.top.forEach((v, i) => {
      console.log(`${i+1}. ${v.name} (${v.votingPower.toFixed(2)}%) - Commission: ${v.commission.toFixed(2)}%`);
    });
    
    if (data.governance.activeProposals.length > 0) {
      console.log("\nActive Governance Proposals:");
      data.governance.activeProposals.forEach(p => {
        console.log(`#${p.id}: ${p.title}`);
        console.log(`  Voting ends: ${new Date(p.votingEndTime).toLocaleString()}`);
      });
    } else {
      console.log("\nNo active governance proposals");
    }
    
    console.log(`\nLast updated: ${data.lastUpdated.toLocaleString()}`);
  } catch (error) {
    console.error("Failed to show dashboard:", error.message);
  }
}

// Run the dashboard
showDashboard();
```

## Conclusion

In this tutorial, you've learned how to:

1. **Enable and generate LCD Client Classes** with Telescope
2. **Use the basic client classes** to query blockchain data
3. **Extend the client classes** with custom methods
4. **Create composite clients** by combining multiple module clients
5. **Add caching** for better performance
6. **Implement error handling and retry logic** for more robust applications
7. **Create a complete dashboard application** using all these techniques

LCD Client Classes provide a powerful foundation for building Cosmos applications. By extending and combining these classes, you can create reusable, maintainable code that interacts with any Cosmos SDK blockchain.

In the next tutorial, we'll explore [RPC Clients](./rpc-clients.md) for more direct and powerful interactions with blockchain nodes. 