# Manual Type Registration

In this tutorial, we'll explore how to manually register custom types with Telescope-generated code. This is a powerful technique that allows you to extend the capabilities of Telescope by integrating custom or third-party types with the generated TypeScript code.

## Understanding Type Registration

When working with Cosmos SDK blockchains, all messages and data structures are defined as Protocol Buffer (protobuf) types. Telescope automatically generates TypeScript representations of these types from protobuf definitions, and registers them in a type registry system that enables serialization, deserialization, and type identification.

However, there are scenarios where you might need to work with types that weren't generated by Telescope:

1. Custom types you've created manually
2. Types from third-party libraries
3. Types for chains or modules not included in your protobuf definitions
4. Specialized types for particular use cases

In these situations, you need to manually register these types to make them work seamlessly with the rest of your Telescope-generated code.

## How Type Registration Works

To understand manual type registration, let's first look at how Telescope registers types automatically. For each message type defined in protobuf, Telescope generates:

1. A TypeScript interface representing the type's structure
2. Methods for encoding, decoding, and creating instances of the type
3. A type URL that uniquely identifies the type (e.g., `/cosmos.bank.v1beta1.MsgSend`)

These types are then collected into registries that pair each type URL with its corresponding implementation:

```typescript
export const registry = [
  ["/cosmos.bank.v1beta1.MsgSend", MsgSend],
  ["/cosmos.staking.v1beta1.MsgDelegate", MsgDelegate],
  // other message types...
];
```

When manually registering types, we're essentially doing the same thing - creating the necessary TypeScript implementation, and adding it to a registry for use in our application.

## Creating a Custom Type

Let's start by creating a custom message type from scratch. For this example, we'll create a simple `CustomMessage` type that might be used in a custom module:

```typescript
// my-custom-types.ts
import { Writer, Reader } from "protobufjs/minimal";

// Define the interface for our custom type
export interface CustomMessage {
  sender: string;
  recipient: string;
  amount: number;
  memo: string;
}

// Create the implementation that satisfies the GeneratedType interface
export const CustomMessage = {
  // The unique type URL
  typeUrl: "/my.custom.v1beta1.CustomMessage",
  
  // Encode method: converts the message into binary format
  encode(message: CustomMessage, writer: Writer = Writer.create()): Writer {
    if (message.sender !== "") {
      writer.uint32(10).string(message.sender);
    }
    if (message.recipient !== "") {
      writer.uint32(18).string(message.recipient);
    }
    if (message.amount !== 0) {
      writer.uint32(24).uint64(message.amount);
    }
    if (message.memo !== "") {
      writer.uint32(34).string(message.memo);
    }
    return writer;
  },
  
  // Decode method: converts binary back into the message object
  decode(input: Reader | Uint8Array, length?: number): CustomMessage {
    const reader = input instanceof Reader ? input : new Reader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = { 
      sender: "", 
      recipient: "", 
      amount: 0, 
      memo: "" 
    } as CustomMessage;
    
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;
        case 2:
          message.recipient = reader.string();
          break;
        case 3:
          message.amount = reader.uint64().toNumber();
          break;
        case 4:
          message.memo = reader.string();
          break;
        default:
          reader.skipType(tag & 7);
          break;
      }
    }
    
    return message;
  },
  
  // fromPartial method: creates a message from a partial object
  fromPartial(object: DeepPartial<CustomMessage>): CustomMessage {
    const message = { 
      sender: "", 
      recipient: "", 
      amount: 0, 
      memo: "" 
    } as CustomMessage;
    
    if (object.sender !== undefined && object.sender !== null) {
      message.sender = object.sender;
    }
    if (object.recipient !== undefined && object.recipient !== null) {
      message.recipient = object.recipient;
    }
    if (object.amount !== undefined && object.amount !== null) {
      message.amount = object.amount;
    }
    if (object.memo !== undefined && object.memo !== null) {
      message.memo = object.memo;
    }
    
    return message;
  }
};

// Helper type for partial objects
type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[P] extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : DeepPartial<T[P]> | T[P];
};
```

This custom type implementation mimics what Telescope would generate, providing methods for encoding, decoding, and creating message instances. The key difference is that we've written it manually instead of having it generated from protobuf.

## Registering a Custom Type

Once we have our custom type, we need to register it to make it usable with CosmJS and Telescope-generated clients. There are several ways to do this:

### Method 1: Adding to an Existing Registry

The simplest approach is to add our custom type to an existing registry:

```typescript
import { registry as bankRegistry } from "./codegen/cosmos/bank/v1beta1/tx";
import { GeneratedType } from "@cosmjs/proto-signing";
import { CustomMessage } from "./my-custom-types";

// Create a new extended registry that includes both the original types and our custom type
const extendedRegistry: Array<[string, GeneratedType]> = [
  ...bankRegistry,
  [CustomMessage.typeUrl, CustomMessage]
];

// Use this extended registry when creating clients
import { SigningStargateClient } from "@cosmjs/stargate";

async function createClientWithCustomType() {
  const client = await SigningStargateClient.connectWithSigner(
    "https://rpc.cosmos.network",
    signer,
    { registry: extendedRegistry }
  );
  
  // Now you can use your custom types with this client
  return client;
}
```

### Method 2: Using the Registry Class

A more flexible approach is to use the `Registry` class from CosmJS, which allows you to add types dynamically:

```typescript
import { Registry } from "@cosmjs/proto-signing";
import { defaultRegistryTypes } from "@cosmjs/stargate";
import { CustomMessage } from "./my-custom-types";

function createRegistryWithCustomTypes() {
  // Start with the default registry types
  const registry = new Registry(defaultRegistryTypes);
  
  // Add our custom type
  registry.register(CustomMessage.typeUrl, CustomMessage);
  
  return registry;
}

// Use the registry
import { SigningStargateClient } from "@cosmjs/stargate";

async function createClient() {
  const registry = createRegistryWithCustomTypes();
  
  const client = await SigningStargateClient.connectWithSigner(
    "https://rpc.cosmos.network",
    signer,
    { registry }
  );
  
  return client;
}
```

### Method 3: Creating a Module Registration Function

For larger applications with many custom types, it's often useful to organize them into module-based registration functions:

```typescript
import { Registry } from "@cosmjs/proto-signing";
import { 
  CustomMessage, 
  AnotherCustomType, 
  YetAnotherType 
} from "./my-custom-types";

// Create a registration function for all types in your custom module
export function registerMyCustomModuleTypes(registry: Registry): void {
  registry.register(CustomMessage.typeUrl, CustomMessage);
  registry.register(AnotherCustomType.typeUrl, AnotherCustomType);
  registry.register(YetAnotherType.typeUrl, YetAnotherType);
}

// Using the registration function
import { Registry } from "@cosmjs/proto-signing";
import { defaultRegistryTypes } from "@cosmjs/stargate";

function createRegistry() {
  const registry = new Registry(defaultRegistryTypes);
  registerMyCustomModuleTypes(registry);
  return registry;
}
```

This approach is modular and maintainable, making it easy to add or remove entire sets of custom types.

## Working with Amino Types

If you're building a DApp that needs to work with wallets (like Keplr) that still use the legacy Amino encoding, you'll also need to register Amino converters for your custom types:

```typescript
import { AminoTypes, AminoConverters } from "@cosmjs/stargate";
import { AminoMsg } from "@cosmjs/amino";
import { CustomMessage } from "./my-custom-types";

// Define the Amino interface for your custom message
interface AminoCustomMessage extends AminoMsg {
  type: "my-module/CustomMessage";
  value: {
    sender: string;
    recipient: string;
    amount: string; // Note: numbers are strings in Amino
    memo: string;
  };
}

// Create the Amino converters
const myCustomAminoConverters: AminoConverters = {
  [CustomMessage.typeUrl]: {
    aminoType: "my-module/CustomMessage",
    toAmino: ({ sender, recipient, amount, memo }: CustomMessage): AminoCustomMessage["value"] => ({
      sender,
      recipient,
      amount: amount.toString(), // Convert number to string for Amino
      memo,
    }),
    fromAmino: ({ sender, recipient, amount, memo }: AminoCustomMessage["value"]): CustomMessage => ({
      sender,
      recipient,
      amount: parseInt(amount, 10), // Convert string back to number
      memo,
    }),
  },
};

// Use the Amino converters with a client
import { SigningStargateClient } from "@cosmjs/stargate";

async function createClient() {
  // Create a registry with our custom types
  const registry = createRegistryWithCustomTypes();
  
  // Create Amino types with our converters
  const aminoTypes = new AminoTypes(myCustomAminoConverters);
  
  // Use both in the client
  const client = await SigningStargateClient.connectWithSigner(
    "https://rpc.cosmos.network",
    signer,
    {
      registry,
      aminoTypes,
    }
  );
  
  return client;
}
```

## Using the Global Decoder Registry

Telescope version 1.0 and later includes a global decoder registry system that can simplify working with different message types:

```typescript
import { GlobalDecoderRegistry } from "./codegen/registry";
import { CustomMessage } from "./my-custom-types";

// Register your custom type
GlobalDecoderRegistry.register(CustomMessage.typeUrl, CustomMessage);

// Later, when you need to decode a message
function decodeAnyMessage(typeUrl: string, binaryData: Uint8Array) {
  return GlobalDecoderRegistry.decode({
    typeUrl,
    value: binaryData
  });
}
```

This is particularly useful when you're dealing with messages of different types and don't know the exact type in advance.

## A Complete Example: Custom NFT Message

Let's put everything together in a complete example. We'll create a custom NFT transfer message, register it, and use it in a transaction:

```typescript
// nft-types.ts
import { Writer, Reader } from "protobufjs/minimal";

// Define our custom NFT transfer message
export interface MsgTransferNFT {
  sender: string;
  recipient: string;
  collectionId: string;
  tokenId: string;
}

// Implement the methods
export const MsgTransferNFT = {
  typeUrl: "/my.nft.v1beta1.MsgTransferNFT",
  
  encode(message: MsgTransferNFT, writer: Writer = Writer.create()): Writer {
    if (message.sender !== "") {
      writer.uint32(10).string(message.sender);
    }
    if (message.recipient !== "") {
      writer.uint32(18).string(message.recipient);
    }
    if (message.collectionId !== "") {
      writer.uint32(26).string(message.collectionId);
    }
    if (message.tokenId !== "") {
      writer.uint32(34).string(message.tokenId);
    }
    return writer;
  },
  
  decode(input: Reader | Uint8Array, length?: number): MsgTransferNFT {
    const reader = input instanceof Reader ? input : new Reader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = { 
      sender: "", 
      recipient: "", 
      collectionId: "", 
      tokenId: "" 
    } as MsgTransferNFT;
    
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;
        case 2:
          message.recipient = reader.string();
          break;
        case 3:
          message.collectionId = reader.string();
          break;
        case 4:
          message.tokenId = reader.string();
          break;
        default:
          reader.skipType(tag & 7);
          break;
      }
    }
    
    return message;
  },
  
  fromPartial(object: DeepPartial<MsgTransferNFT>): MsgTransferNFT {
    const message = { 
      sender: "", 
      recipient: "", 
      collectionId: "", 
      tokenId: "" 
    } as MsgTransferNFT;
    
    if (object.sender !== undefined && object.sender !== null) {
      message.sender = object.sender;
    }
    if (object.recipient !== undefined && object.recipient !== null) {
      message.recipient = object.recipient;
    }
    if (object.collectionId !== undefined && object.collectionId !== null) {
      message.collectionId = object.collectionId;
    }
    if (object.tokenId !== undefined && object.tokenId !== null) {
      message.tokenId = object.tokenId;
    }
    
    return message;
  }
};

// Also define the Amino converter
import { AminoMsg } from "@cosmjs/amino";

export interface AminoMsgTransferNFT extends AminoMsg {
  type: "my-nft/TransferNFT";
  value: {
    sender: string;
    recipient: string;
    collection_id: string; // Note: snake_case in Amino
    token_id: string;
  };
}

export const aminoConverters = {
  [MsgTransferNFT.typeUrl]: {
    aminoType: "my-nft/TransferNFT",
    toAmino: ({ sender, recipient, collectionId, tokenId }: MsgTransferNFT): AminoMsgTransferNFT["value"] => ({
      sender,
      recipient,
      collection_id: collectionId, // Convert to snake_case
      token_id: tokenId,
    }),
    fromAmino: ({ sender, recipient, collection_id, token_id }: AminoMsgTransferNFT["value"]): MsgTransferNFT => ({
      sender,
      recipient,
      collectionId: collection_id, // Convert back to camelCase
      tokenId: token_id,
    }),
  },
};

// Helper type
type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[P] extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : DeepPartial<T[P]> | T[P];
};
```

Now, let's use this custom NFT message in an application:

```typescript
// nft-app.ts
import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
import { SigningStargateClient, AminoTypes, defaultRegistryTypes } from "@cosmjs/stargate";
import { Registry } from "@cosmjs/proto-signing";
import { MsgTransferNFT, aminoConverters } from "./nft-types";

async function transferNFT(
  mnemonic: string,
  recipientAddress: string,
  collectionId: string,
  tokenId: string
) {
  try {
    // Create a wallet
    const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic, {
      prefix: "cosmos", // Use the appropriate address prefix for your chain
    });
    
    // Get the sender address
    const [account] = await wallet.getAccounts();
    const sender = account.address;
    
    // Create a registry with our custom NFT message type
    const registry = new Registry(defaultRegistryTypes);
    registry.register(MsgTransferNFT.typeUrl, MsgTransferNFT);
    
    // Set up Amino types for legacy wallet support
    const aminoTypes = new AminoTypes(aminoConverters);
    
    // Create a signing client
    const client = await SigningStargateClient.connectWithSigner(
      "https://rpc.your-cosmos-chain.com", // Replace with your chain's RPC endpoint
      wallet,
      { registry, aminoTypes }
    );
    
    // Prepare the NFT transfer message
    const transferMsg = {
      typeUrl: MsgTransferNFT.typeUrl,
      value: MsgTransferNFT.fromPartial({
        sender,
        recipient: recipientAddress,
        collectionId,
        tokenId,
      }),
    };
    
    // Define the fee
    const fee = {
      amount: [{ denom: "uatom", amount: "5000" }], // Use appropriate denom and amount
      gas: "200000",
    };
    
    // Broadcast the transaction
    console.log("Sending NFT transfer transaction...");
    const result = await client.signAndBroadcast(
      sender,
      [transferMsg],
      fee,
      "Transferring NFT"
    );
    
    // Check the result
    if (result.code === 0) {
      console.log("NFT transfer successful!");
      console.log("Transaction hash:", result.transactionHash);
    } else {
      console.error("NFT transfer failed:", result.rawLog);
    }
    
    return result;
  } catch (error) {
    console.error("Error transferring NFT:", error);
    throw error;
  }
}

// Example usage
transferNFT(
  "your mnemonic phrase here",
  "cosmos1recipient...",
  "my-awesome-collection-1",
  "token-123"
).catch(console.error);
```

## Tips and Best Practices

When manually registering types, follow these best practices for the best results:

### 1. Follow Protobuf Encoding Rules

Your manual encode and decode methods should follow the same protobuf encoding rules as generated code. This includes field numbers, wire types, and appropriate type handling.

### 2. Use Consistent Type URLs

Choose type URLs that follow the standard pattern:
- `/namespace.module.version.TypeName`
- Example: `/my.nft.v1beta1.MsgTransferNFT`

### 3. Organize Types by Module

Group related types together in module-specific files and registration functions for better organization:

```typescript
// Register all bank-related types
export function registerBankTypes(registry: Registry): void {
  registry.register("/my.bank.v1beta1.TypeA", TypeA);
  registry.register("/my.bank.v1beta1.TypeB", TypeB);
}

// Register all staking-related types
export function registerStakingTypes(registry: Registry): void {
  registry.register("/my.staking.v1beta1.TypeC", TypeC);
  registry.register("/my.staking.v1beta1.TypeD", TypeD);
}
```

### 4. Include TypeScript Types

Always define TypeScript interfaces for your custom types to get full type checking and IDE support:

```typescript
// Good: With TypeScript interface
export interface MyType {
  field1: string;
  field2: number;
}

// Avoid: Without TypeScript interface
export const MyType = {
  typeUrl: "...",
  encode: (message: any) => { /* ... */ },
  // ...
};
```

### 5. Implement All Required Methods

Make sure your custom types have all required methods:
- `encode`
- `decode`
- `fromPartial`
- (Optional) `fromJSON` and `toJSON`

### 6. Test Your Custom Types

Always test your custom types thoroughly to ensure they encode and decode correctly:

```typescript
function testCustomType() {
  // Create a message
  const original = MsgTransferNFT.fromPartial({
    sender: "sender123",
    recipient: "recipient456",
    collectionId: "collection789",
    tokenId: "token012"
  });
  
  // Encode to binary
  const binary = MsgTransferNFT.encode(original).finish();
  
  // Decode back
  const decoded = MsgTransferNFT.decode(binary);
  
  // Verify fields match
  console.assert(original.sender === decoded.sender, "Sender mismatch");
  console.assert(original.recipient === decoded.recipient, "Recipient mismatch");
  console.assert(original.collectionId === decoded.collectionId, "Collection ID mismatch");
  console.assert(original.tokenId === decoded.tokenId, "Token ID mismatch");
  
  console.log("Test passed!");
}
```

### 7. Register Both Proto and Amino Types

If your application needs to work with wallets, make sure to register both Proto and Amino converters.

## Conclusion

Manual type registration allows you to extend Telescope's capabilities by integrating custom types with the generated code. This is essential when working with specialized modules, non-standard types, or extending chain functionality.

By following the patterns and best practices outlined in this tutorial, you can seamlessly blend custom types with Telescope-generated code, creating a unified and type-safe experience for your Cosmos SDK application.

In the next tutorial, we'll explore [JSON Patch Protos](./json-patch-protos.md) for modifying Protocol Buffer definitions without changing the original files. 