# Understanding and Using RPC Clients

In this tutorial, we'll explore how to use RPC (Remote Procedure Call) clients generated by Telescope to interact with Cosmos SDK blockchains. RPC clients provide powerful and direct access to blockchain nodes, allowing your applications to query data and subscribe to real-time events.

## What Are RPC Clients?

RPC clients allow your application to make direct calls to blockchain nodes, giving you access to the full range of functionality provided by Cosmos SDK chains. Telescope generates type-safe TypeScript clients that make these interactions simpler and less error-prone.

There are three main types of RPC clients that Telescope can generate:

1. **Tendermint RPC Client** - The most direct and powerful interface to Tendermint nodes
2. **gRPC-web Client** - Browser-compatible gRPC client
3. **gRPC-gateway Client** - REST-based access to gRPC services

In this tutorial, we'll learn how to use each of these client types and understand their strengths and best use cases.

## Setting Up Your Project

First, let's enable RPC client generation in your Telescope configuration:

```typescript
// In your Telescope configuration file
import { TelescopeOptions } from "@cosmology/types";

const options: TelescopeOptions = {
  rpcClients: {
    enabled: true,
    camelCase: true // Makes method names more JavaScript-friendly
  }
  // Other Telescope options...
};

export default options;
```

After running Telescope with this configuration, it will generate RPC client code for all the modules in your Protobuf definitions.

## Creating Your First RPC Client

Let's start by creating a basic RPC client to connect to the Cosmos Hub:

```typescript
import { createRPCQueryClient } from "./codegen/rpc";

async function main() {
  try {
    // Create an RPC client
    console.log("Connecting to Cosmos Hub...");
    const client = await createRPCQueryClient({
      rpcEndpoint: "https://rpc.cosmos.network"
    });
    
    console.log("Connected successfully!");
    
    // Let's get some basic information about the chain
    const nodeInfo = await client.cosmos.base.tendermint.v1beta1.getNodeInfo({});
    console.log("Connected to chain:", nodeInfo.defaultNodeInfo.network);
    console.log("Node version:", nodeInfo.applicationVersion.version);
    
    // Query the latest block
    const latestBlock = await client.cosmos.base.tendermint.v1beta1.getLatestBlock({});
    console.log("Latest block height:", latestBlock.block.header.height);
    console.log("Latest block time:", new Date(latestBlock.block.header.time).toLocaleString());
    
    // Get some information about validators
    const { validators } = await client.cosmos.staking.v1beta1.validators({
      status: "BOND_STATUS_BONDED"
    });
    
    console.log(`Found ${validators.length} active validators`);
    
    // Show the top 5 validators by voting power
    console.log("\nTop validators:");
    validators
      .sort((a, b) => parseInt(b.tokens) - parseInt(a.tokens))
      .slice(0, 5)
      .forEach((validator, index) => {
        console.log(`${index + 1}. ${validator.description.moniker}`);
        console.log(`   Voting power: ${parseInt(validator.tokens) / 1_000_000} ATOM`);
      });
  } catch (error) {
    console.error("Error connecting to the blockchain:", error.message);
  }
}

main();
```

## Understanding the Tendermint RPC Client

The Tendermint RPC client provides the most direct access to Tendermint nodes. It's great for server-side applications that need high-performance and access to real-time events.

```typescript
import { createRPCQueryClient } from "./codegen/rpc";
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";

async function exploreTemdermintRPC() {
  try {
    // Create a client with explicit client type
    const client = await createRPCQueryClient({
      rpcEndpoint: "https://rpc.cosmos.network",
      clientType: "tendermint" // Explicitly specify Tendermint client
    });
    
    // You can also create a raw Tendermint client for advanced use cases
    const tmClient = await Tendermint34Client.connect("https://rpc.cosmos.network");
    
    // Get the status of the node
    const status = await tmClient.status();
    console.log("Node status:");
    console.log("- Chain ID:", status.nodeInfo.network);
    console.log("- Latest block:", status.syncInfo.latestBlockHeight);
    console.log("- Catching up:", status.syncInfo.catchingUp);
    
    // Get a specific block
    const blockHeight = 9000000; // Choose a block height
    const block = await tmClient.block(blockHeight);
    
    console.log(`\nBlock #${blockHeight}:`);
    console.log("- Time:", new Date(block.block.header.time).toLocaleString());
    console.log("- Proposer:", block.block.header.proposerAddress);
    console.log("- Number of transactions:", block.block.txs.length);
    
    // Get network information
    const netInfo = await tmClient.netInfo();
    console.log("\nNetwork information:");
    console.log("- Number of peers:", netInfo.nPeers);
    console.log("- Is listening:", netInfo.listening);
    
    // Always disconnect when done
    tmClient.disconnect();
  } catch (error) {
    console.error("Error exploring Tendermint RPC:", error.message);
  }
}
```

## Working with gRPC-web Client

For browser applications, the gRPC-web client provides a compatible interface:

```typescript
import { createRPCQueryClient } from "./codegen/rpc";

async function browserCompatibleQueries() {
  try {
    // Create a gRPC-web client for browser compatibility
    const client = await createRPCQueryClient({
      rpcEndpoint: "https://grpc-web.cosmos.network",
      clientType: "grpc-web"
    });
    
    // Query account balances
    const address = "cosmos1..."; // Replace with a real address
    const { balances } = await client.cosmos.bank.v1beta1.allBalances({
      address
    });
    
    console.log(`Account ${address} balances:`);
    if (balances.length === 0) {
      console.log("No tokens found");
    } else {
      balances.forEach(coin => {
        console.log(`${coin.amount} ${coin.denom}`);
      });
    }
    
    // Query governance proposals
    const { proposals } = await client.cosmos.gov.v1beta1.proposals({});
    
    console.log(`\nFound ${proposals.length} governance proposals:`);
    proposals.forEach(proposal => {
      console.log(`- #${proposal.proposalId}: ${proposal.content.title}`);
      console.log(`  Status: ${getProposalStatus(proposal.status)}`);
      console.log(`  Voting ends: ${new Date(proposal.votingEndTime).toLocaleString()}`);
    });
  } catch (error) {
    console.error("Error in browser-compatible queries:", error.message);
  }
}

// Helper function to convert proposal status to readable form
function getProposalStatus(status) {
  const statuses = [
    "UNSPECIFIED",
    "DEPOSIT_PERIOD",
    "VOTING_PERIOD",
    "PASSED",
    "REJECTED",
    "FAILED"
  ];
  return statuses[status] || "UNKNOWN";
}
```

## Using gRPC-gateway Client

The gRPC-gateway client provides a REST-based interface to gRPC services:

```typescript
import { createRPCQueryClient } from "./codegen/rpc";

async function restBasedQueries() {
  try {
    // Create a gRPC-gateway client (REST-based)
    const client = await createRPCQueryClient({
      rpcEndpoint: "https://rest.cosmos.network",
      clientType: "grpc-gateway"
    });
    
    // Query inflation rate
    const inflation = await client.cosmos.mint.v1beta1.inflation({});
    const inflationRate = parseFloat(inflation.inflation) * 100;
    console.log(`Current inflation rate: ${inflationRate.toFixed(2)}%`);
    
    // Query total supply
    const { supply } = await client.cosmos.bank.v1beta1.totalSupply({});
    
    console.log("\nTotal supply:");
    supply.forEach(coin => {
      if (coin.denom === "uatom") {
        const atomAmount = parseInt(coin.amount) / 1_000_000;
        console.log(`${atomAmount.toLocaleString()} ATOM`);
      } else {
        console.log(`${coin.amount} ${coin.denom}`);
      }
    });
  } catch (error) {
    console.error("Error in REST-based queries:", error.message);
  }
}
```

## Handling Pagination

Many RPC methods return large datasets that are paginated. Here's how to work with pagination:

```typescript
import { createRPCQueryClient } from "./codegen/rpc";

async function handlePagination() {
  try {
    const client = await createRPCQueryClient({
      rpcEndpoint: "https://rpc.cosmos.network"
    });
    
    // Example 1: Using offset-based pagination
    console.log("Using offset-based pagination:");
    let pageNumber = 1;
    const pageSize = 10;
    
    const firstPage = await client.cosmos.staking.v1beta1.validators({
      pagination: {
        offset: "0",
        limit: pageSize.toString(),
        countTotal: true
      }
    });
    
    console.log(`Page ${pageNumber}: ${firstPage.validators.length} validators`);
    console.log(`Total validators: ${firstPage.pagination.total}`);
    
    // Fetch second page
    pageNumber++;
    const secondPage = await client.cosmos.staking.v1beta1.validators({
      pagination: {
        offset: pageSize.toString(),
        limit: pageSize.toString()
      }
    });
    
    console.log(`Page ${pageNumber}: ${secondPage.validators.length} validators`);
    
    // Example 2: Using key-based pagination (more efficient for large datasets)
    console.log("\nUsing key-based pagination:");
    
    // Function to get all validators using key-based pagination
    async function getAllValidators() {
      let allValidators = [];
      let nextKey = null;
      let pageCount = 0;
      
      do {
        pageCount++;
        // Set up pagination parameters
        const paginationParams = nextKey 
          ? { key: nextKey, limit: "50" } 
          : { limit: "50" };
        
        // Make the query
        const response = await client.cosmos.staking.v1beta1.validators({
          pagination: paginationParams
        });
        
        // Add this page of validators to our result
        allValidators = [...allValidators, ...response.validators];
        
        // Get the key for the next page
        nextKey = response.pagination?.nextKey || null;
        
        console.log(`Page ${pageCount}: fetched ${response.validators.length} validators, running total: ${allValidators.length}`);
        
      } while (nextKey && nextKey.length > 0);
      
      return allValidators;
    }
    
    const allValidators = await getAllValidators();
    console.log(`Retrieved all ${allValidators.length} validators`);
  } catch (error) {
    console.error("Error handling pagination:", error.message);
  }
}
```

## Subscribing to Real-time Events

One of the powerful features of Tendermint RPC is the ability to subscribe to real-time events. Let's see how to subscribe to new blocks:

```typescript
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";

async function subscribeToEvents() {
  let tmClient;
  try {
    console.log("Connecting to Tendermint WebSocket...");
    tmClient = await Tendermint34Client.connect("wss://rpc.cosmos.network/websocket");
    console.log("Connected! Subscribing to events...");
    
    // Subscribe to new blocks
    console.log("Subscribing to new blocks...");
    const blockSubscription = tmClient.subscribeNewBlock().subscribe({
      next: (block) => {
        console.log(`New block #${block.header.height} at ${new Date(block.header.time).toLocaleString()}`);
        console.log(`Contains ${block.txs.length} transactions`);
      },
      error: (err) => {
        console.error("Block subscription error:", err.message);
      },
      complete: () => {
        console.log("Block subscription completed");
      }
    });
    
    // Subscribe to transactions
    console.log("Subscribing to transactions...");
    const txSubscription = tmClient.subscribeTx().subscribe({
      next: (txEvent) => {
        console.log(`New transaction: ${Buffer.from(txEvent.hash).toString('hex')}`);
        console.log(`Result code: ${txEvent.result.code} (${txEvent.result.code === 0 ? "success" : "failed"})`);
      },
      error: (err) => {
        console.error("Transaction subscription error:", err.message);
      }
    });
    
    // Keep the subscription active for a minute
    console.log("Watching for events for 60 seconds...");
    await new Promise(resolve => setTimeout(resolve, 60000));
    
    // Unsubscribe when done
    console.log("Unsubscribing...");
    blockSubscription.unsubscribe();
    txSubscription.unsubscribe();
    
  } catch (error) {
    console.error("Error in event subscription:", error.message);
  } finally {
    // Always disconnect the client
    if (tmClient) {
      console.log("Disconnecting...");
      tmClient.disconnect();
    }
  }
}
```

## Error Handling and Retries

In production applications, you'll want to handle errors gracefully and implement retries for transient failures:

```typescript
import { createRPCQueryClient } from "./codegen/rpc";

async function queryWithRetries(endpoint, queryFn, maxRetries = 3) {
  let client;
  try {
    client = await createRPCQueryClient({
      rpcEndpoint: endpoint
    });
    
    let attempt = 0;
    while (attempt < maxRetries) {
      try {
        attempt++;
        console.log(`Attempt ${attempt}/${maxRetries}...`);
        
        // Execute the provided query function with the client
        const result = await queryFn(client);
        return result; // Success!
      } catch (error) {
        if (attempt >= maxRetries) {
          console.error(`All ${maxRetries} attempts failed`);
          throw error; // Re-throw after all attempts
        }
        
        // Determine if we should retry based on the error
        if (isRetriableError(error)) {
          const delay = calculateBackoff(attempt);
          console.warn(`Retriable error: ${error.message}. Retrying in ${delay}ms...`);
          await new Promise(resolve => setTimeout(resolve, delay));
        } else {
          console.error(`Non-retriable error: ${error.message}`);
          throw error; // Don't retry non-retriable errors
        }
      }
    }
  } finally {
    // Clean up resources if needed
  }
}

// Helper function to determine if an error is retriable
function isRetriableError(error) {
  // Network errors or server errors (5xx) are generally retriable
  return (
    !error.response || // Network error
    error.code === 4 || // DEADLINE_EXCEEDED
    error.code === 14 || // UNAVAILABLE
    (error.response && error.response.status >= 500) // Server error
  );
}

// Helper function for exponential backoff
function calculateBackoff(attempt) {
  const baseDelay = 1000; // 1 second
  return baseDelay * Math.pow(2, attempt - 1); // 1s, 2s, 4s, 8s, etc.
}

// Example usage
async function performResilientQuery() {
  try {
    // Define the query we want to execute with retry logic
    const result = await queryWithRetries(
      "https://rpc.cosmos.network",
      async (client) => {
        const { validators } = await client.cosmos.staking.v1beta1.validators({
          status: "BOND_STATUS_BONDED"
        });
        return validators;
      },
      3 // Maximum 3 retries
    );
    
    console.log(`Successfully queried ${result.length} validators`);
  } catch (error) {
    console.error("Query ultimately failed:", error.message);
  }
}
```

## Building a Chain Explorer Dashboard

Let's put everything together and build a simple blockchain explorer dashboard:

```typescript
import { createRPCQueryClient } from "./codegen/rpc";

async function createBlockchainDashboard() {
  try {
    console.log("Connecting to Cosmos Hub...");
    const client = await createRPCQueryClient({
      rpcEndpoint: "https://rpc.cosmos.network"
    });
    
    // Fetch multiple pieces of data in parallel for efficiency
    const [
      nodeInfo,
      latestBlock,
      validatorsResponse,
      stakingParams,
      inflation,
      supplyResponse,
      govProposals
    ] = await Promise.all([
      client.cosmos.base.tendermint.v1beta1.getNodeInfo({}),
      client.cosmos.base.tendermint.v1beta1.getLatestBlock({}),
      client.cosmos.staking.v1beta1.validators({ status: "BOND_STATUS_BONDED" }),
      client.cosmos.staking.v1beta1.params({}),
      client.cosmos.mint.v1beta1.inflation({}),
      client.cosmos.bank.v1beta1.totalSupply({}),
      client.cosmos.gov.v1beta1.proposals({ proposalStatus: 2 }) // Voting period
    ]);
    
    // Extract and process the data
    const chainId = nodeInfo.defaultNodeInfo.network;
    const nodeVersion = nodeInfo.applicationVersion.version;
    const blockHeight = latestBlock.block.header.height;
    const blockTime = new Date(latestBlock.block.header.time);
    
    const validators = validatorsResponse.validators;
    const bondedTokens = stakingParams.params.bondDenom;
    
    // Calculate inflation
    const inflationRate = parseFloat(inflation.inflation) * 100;
    
    // Get ATOM supply
    const atomSupply = supplyResponse.supply.find(coin => coin.denom === "uatom");
    const totalAtoms = atomSupply 
      ? parseInt(atomSupply.amount) / 1_000_000
      : 0;
    
    // Get active proposals
    const activeProposals = govProposals.proposals;
    
    // Display the dashboard
    console.log(`\n===== ${chainId} Blockchain Dashboard =====`);
    console.log(`Current Time: ${new Date().toLocaleString()}`);
    console.log("\n--- Network Information ---");
    console.log(`Node Version: ${nodeVersion}`);
    console.log(`Latest Block: ${blockHeight}`);
    console.log(`Block Time: ${blockTime.toLocaleString()}`);
    console.log(`Time Since Last Block: ${Math.round((Date.now() - blockTime.getTime()) / 1000)} seconds`);
    
    console.log("\n--- Validator Information ---");
    console.log(`Active Validators: ${validators.length}`);
    console.log(`Bonded Token Denom: ${bondedTokens}`);
    
    console.log("\nTop 5 Validators by Voting Power:");
    validators
      .sort((a, b) => parseInt(b.tokens) - parseInt(a.tokens))
      .slice(0, 5)
      .forEach((v, i) => {
        const votingPower = parseInt(v.tokens) / 1_000_000;
        const votingPercent = (votingPower / totalAtoms * 100).toFixed(2);
        console.log(`${i+1}. ${v.description.moniker} - ${votingPower.toLocaleString()} ATOM (${votingPercent}%)`);
      });
    
    console.log("\n--- Economic Information ---");
    console.log(`Total Supply: ${totalAtoms.toLocaleString()} ATOM`);
    console.log(`Inflation Rate: ${inflationRate.toFixed(2)}%`);
    
    console.log("\n--- Governance Information ---");
    console.log(`Active Proposals: ${activeProposals.length}`);
    
    if (activeProposals.length > 0) {
      console.log("\nProposals in Voting Period:");
      activeProposals.forEach(p => {
        console.log(`- Proposal #${p.proposalId}: ${p.content.title}`);
        console.log(`  Voting Ends: ${new Date(p.votingEndTime).toLocaleString()}`);
      });
    }
    
    console.log("\n========================================");
  } catch (error) {
    console.error("Error creating dashboard:", error.message);
  }
}

createBlockchainDashboard();
```

## Choosing the Right Client Type

Here's a guide to help you choose the right client type for your application:

1. **Tendermint RPC Client**
   - Best for: Server-side applications, applications that need real-time data via subscriptions
   - Pros: Most direct and efficient, supports WebSocket subscriptions
   - Cons: Limited browser compatibility (WebSocket only)

2. **gRPC-web Client**
   - Best for: Browser applications that need efficient querying
   - Pros: Works in browsers, more efficient than REST
   - Cons: Limited subscription support, requires special proxy in production

3. **gRPC-gateway Client**
   - Best for: Simple browser applications, when compatibility is most important
   - Pros: Works everywhere, standard REST interface
   - Cons: Less efficient, no subscription support

## Best Practices

Here are some best practices to follow when using RPC clients:

1. **Manage Client Lifecycle**: Always create and dispose of clients properly
2. **Use Pagination**: For large datasets, implement proper pagination
3. **Batch Requests**: Use Promise.all to execute multiple queries in parallel
4. **Handle Errors**: Implement proper error handling with retries for transient failures
5. **Rate Limiting**: Be mindful of rate limits on public nodes
6. **Connection Pooling**: Reuse clients instead of creating new ones for each request
7. **Timeout Management**: Set appropriate timeouts for different operations

## Conclusion

In this tutorial, you've learned how to:

1. Configure Telescope to generate RPC clients
2. Create and use different types of RPC clients
3. Query blockchain data with type safety
4. Handle pagination for large datasets
5. Subscribe to real-time blockchain events
6. Implement error handling and retries
7. Build a complete blockchain explorer dashboard

RPC clients provide powerful and direct access to blockchain nodes. By using Telescope-generated clients, you get the benefits of this power combined with the safety and convenience of TypeScript's type system.

In the next tutorial, we'll explore [RPC Client Classes](./rpc-client-classes.md) for more advanced and object-oriented usage patterns. 