# Working with RPC Client Classes

In this tutorial, we'll explore RPC Client Classes generated by Telescope, which provide an object-oriented approach to interacting with Cosmos SDK blockchains. These classes offer enhanced flexibility and extensibility compared to regular RPC clients.

## Understanding RPC Client Classes

RPC Client Classes take the functionality of standard RPC clients (covered in the [previous tutorial](./rpc-clients.md)) and wrap them in a class-based architecture. This approach offers several advantages:

1. **Extensibility**: You can easily extend the classes to add custom methods
2. **Encapsulation**: Implementation details are hidden behind a clean interface
3. **Testability**: Classes are easier to mock and test
4. **Composition**: You can create composite clients by combining multiple module clients

Let's dive in and see how to use these classes in your applications.

## Setting Up Your Project

First, let's enable RPC Client Classes generation in your Telescope configuration:

```typescript
// In your Telescope configuration file
import { TelescopeOptions } from "@cosmology/types";

const options: TelescopeOptions = {
  rpcClientClasses: {
    enabled: true,
    camelCase: true // Makes method names more JavaScript-friendly
  }
  // Other Telescope options...
};

export default options;
```

After running Telescope with this configuration, it will generate RPC Client Classes for all modules in your Protobuf definitions.

## Creating Your First RPC Client Classes

Let's start by creating a basic set of client classes to query the Cosmos Hub:

```typescript
import { createRPCQueryClientClasses } from "./codegen/client-classes";

async function main() {
  try {
    // Create client classes
    console.log("Creating RPC client classes...");
    const clients = createRPCQueryClientClasses({
      rpcEndpoint: "https://rpc.cosmos.network"
    });
    
    console.log("Client classes created successfully!");
    
    // Access specific module clients
    const bankClient = clients.cosmos.bank.v1beta1;
    const stakingClient = clients.cosmos.staking.v1beta1;
    const governanceClient = clients.cosmos.gov.v1beta1;
    
    // Use the bank client to query account balances
    const address = "cosmos1..."; // Replace with a real address
    const { balances } = await bankClient.allBalances({ address });
    
    console.log(`Account ${address} has:`);
    balances.forEach(coin => {
      console.log(`- ${coin.amount} ${coin.denom}`);
    });
    
    // Use the staking client to query validators
    const { validators } = await stakingClient.validators({
      status: "BOND_STATUS_BONDED"
    });
    
    console.log(`\nFound ${validators.length} active validators`);
    console.log("Top 3 validators by voting power:");
    
    validators
      .sort((a, b) => parseInt(b.tokens) - parseInt(a.tokens))
      .slice(0, 3)
      .forEach((validator, index) => {
        console.log(`${index + 1}. ${validator.description.moniker}`);
        console.log(`   Voting power: ${parseInt(validator.tokens) / 1_000_000} ATOM`);
      });
    
    // Use the governance client to query proposals
    const { proposals } = await governanceClient.proposals({});
    
    console.log(`\nFound ${proposals.length} governance proposals`);
    if (proposals.length > 0) {
      console.log("Latest proposals:");
      proposals.slice(0, 3).forEach(proposal => {
        console.log(`- #${proposal.proposalId}: ${proposal.content.title}`);
      });
    }
  } catch (error) {
    console.error("Error:", error.message);
  }
}

main();
```

## Exploring the Client Classes Structure

Let's take a look at the structure of these client classes:

```typescript
import { createRPCQueryClientClasses } from "./codegen/client-classes";

async function exploreClientStructure() {
  const clients = createRPCQueryClientClasses({
    rpcEndpoint: "https://rpc.cosmos.network"
  });
  
  // The clients object has a nested structure that mirrors the protobuf packages
  console.log("Client structure:");
  
  // First level: namespace (e.g., cosmos, osmosis)
  const namespaces = Object.keys(clients);
  console.log("Available namespaces:", namespaces);
  
  // Second level: modules (e.g., bank, staking)
  const cosmosModules = Object.keys(clients.cosmos);
  console.log("\nCosmos modules:", cosmosModules);
  
  // Third level: versions (e.g., v1beta1)
  const bankVersions = Object.keys(clients.cosmos.bank);
  console.log("\nBank module versions:", bankVersions);
  
  // Fourth level: the actual client class instance
  const bankClient = clients.cosmos.bank.v1beta1;
  
  // Examine methods available on the bank client
  console.log("\nBank client methods:");
  console.log(Object.getOwnPropertyNames(
    Object.getPrototypeOf(bankClient)
  ).filter(name => name !== 'constructor'));
  
  // Log the type of the client
  console.log("\nClient type:", bankClient.constructor.name);
}

exploreClientStructure();
```

## Understanding Different Client Types

RPC Client Classes support different underlying RPC implementations. Let's examine each:

```typescript
import { createRPCQueryClientClasses } from "./codegen/client-classes";

async function compareClientTypes() {
  console.log("Creating clients with different implementations...");
  
  // 1. Tendermint RPC Client (default)
  const tendermintClients = createRPCQueryClientClasses({
    rpcEndpoint: "https://rpc.cosmos.network",
    clientType: "tendermint"
  });
  
  // 2. gRPC-web Client (for browsers)
  const grpcWebClients = createRPCQueryClientClasses({
    rpcEndpoint: "https://grpc-web.cosmos.network",
    clientType: "grpc-web"
  });
  
  // 3. gRPC-gateway Client (REST-based)
  const grpcGatewayClients = createRPCQueryClientClasses({
    rpcEndpoint: "https://rest.cosmos.network",
    clientType: "grpc-gateway"
  });
  
  console.log("All client types created successfully!");
  
  // Use each client type to perform the same query
  const address = "cosmos1..."; // Replace with a real address
  
  try {
    console.log("\nQuerying with Tendermint client:");
    const tendermintResult = await tendermintClients.cosmos.bank.v1beta1.balance({
      address,
      denom: "uatom"
    });
    console.log("Result:", tendermintResult.balance);
    
    console.log("\nQuerying with gRPC-web client:");
    const grpcWebResult = await grpcWebClients.cosmos.bank.v1beta1.balance({
      address,
      denom: "uatom"
    });
    console.log("Result:", grpcWebResult.balance);
    
    console.log("\nQuerying with gRPC-gateway client:");
    const grpcGatewayResult = await grpcGatewayClients.cosmos.bank.v1beta1.balance({
      address,
      denom: "uatom"
    });
    console.log("Result:", grpcGatewayResult.balance);
    
    console.log("\nAll client types work with the same interface!");
  } catch (error) {
    console.error("Error during comparison:", error.message);
  }
}

compareClientTypes();
```

## Extending Client Classes

One of the main advantages of using client classes is the ability to extend them with custom functionality. Let's create an extended bank client:

```typescript
import { createRPCQueryClientClasses } from "./codegen/client-classes";
import { BankQueryClient } from "./codegen/cosmos/bank/v1beta1/query.rpc.Query";

// Create an extended bank client with additional methods
class EnhancedBankClient extends BankQueryClient {
  // Add utility method to convert micro units to display units
  convertToDisplayUnits(microAmount, decimals = 6) {
    return Number(microAmount) / Math.pow(10, decimals);
  }
  
  // Get formatted balance that's easy to read
  async getFormattedBalance(address, denom) {
    const { balance } = await this.balance({
      address,
      denom
    });
    
    // If balance not found or zero
    if (!balance || balance.amount === "0") {
      return `0 ${this.getDenomName(denom)}`;
    }
    
    // Convert amount based on denomination
    const displayAmount = this.convertToDisplayUnits(balance.amount);
    const displayDenom = this.getDenomName(denom);
    
    return `${displayAmount.toLocaleString()} ${displayDenom}`;
  }
  
  // Get account summary with total value in specified denomination
  async getAccountSummary(address) {
    const { balances } = await this.allBalances({
      address
    });
    
    // Process each balance to add more information
    const processedBalances = balances.map(coin => {
      const displayAmount = this.convertToDisplayUnits(coin.amount);
      const displayDenom = this.getDenomName(coin.denom);
      
      return {
        denom: coin.denom,
        displayDenom,
        rawAmount: coin.amount,
        displayAmount,
        formatted: `${displayAmount.toLocaleString()} ${displayDenom}`
      };
    });
    
    // Calculate total (if there are tokens)
    const total = processedBalances.reduce(
      (sum, coin) => sum + coin.displayAmount,
      0
    );
    
    return {
      address,
      balances: processedBalances,
      totalBalances: processedBalances.length,
      totalValue: total.toLocaleString(),
      hasBalance: total > 0
    };
  }
  
  // Helper method to convert denomination to display name
  getDenomName(denom) {
    // Handle common denoms
    if (denom === "uatom") return "ATOM";
    if (denom === "uosmo") return "OSMO";
    if (denom === "ujuno") return "JUNO";
    if (denom === "uluna") return "LUNA";
    
    // For other micro denoms, remove the 'u' prefix and capitalize
    if (denom.startsWith("u")) {
      return denom.substring(1).toUpperCase();
    }
    
    // For IBC tokens, simplify
    if (denom.startsWith("ibc/")) {
      return "IBC Token";
    }
    
    // Default case: just return the original denom
    return denom;
  }
}

// Usage example
async function useEnhancedClient() {
  // Create the base client classes
  const baseClients = await createRPCQueryClientClasses({
    rpcEndpoint: "https://rpc.cosmos.network"
  });
  
  // Extract the underlying clients needed for our enhanced client
  const { rpc, queryClient } = baseClients.cosmos.bank.v1beta1;
  
  // Create our enhanced client
  const enhancedBank = new EnhancedBankClient(rpc, queryClient);
  
  // Use our enhanced methods
  const address = "cosmos1..."; // Replace with a real address
  
  try {
    // Get formatted balance
    const formattedAtom = await enhancedBank.getFormattedBalance(address, "uatom");
    console.log(`ATOM Balance: ${formattedAtom}`);
    
    // Get account summary
    const summary = await enhancedBank.getAccountSummary(address);
    
    console.log("\nAccount Summary:");
    console.log(`Address: ${summary.address}`);
    console.log(`Total Value: ${summary.totalValue}`);
    console.log(`Number of tokens: ${summary.totalBalances}`);
    
    if (summary.balances.length > 0) {
      console.log("\nToken Balances:");
      summary.balances.forEach(balance => {
        console.log(`- ${balance.formatted}`);
      });
    } else {
      console.log("\nNo tokens found in this account.");
    }
  } catch (error) {
    console.error("Error using enhanced client:", error.message);
  }
}

useEnhancedClient();
```

## Creating a Composite Client

For applications that work with multiple modules, you can create a composite client:

```typescript
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";
import { QueryClient } from "@cosmjs/stargate";
import { BankQueryClient } from "./codegen/cosmos/bank/v1beta1/query.rpc.Query";
import { StakingQueryClient } from "./codegen/cosmos/staking/v1beta1/query.rpc.Query";
import { DistributionQueryClient } from "./codegen/cosmos/distribution/v1beta1/query.rpc.Query";

// Create a composite client for account portfolio information
class AccountPortfolioClient {
  private readonly bankClient: BankQueryClient;
  private readonly stakingClient: StakingQueryClient;
  private readonly distributionClient: DistributionQueryClient;
  private readonly tendermintClient: Tendermint34Client;
  
  // Factory method to create and connect the client
  static async connect(rpcEndpoint: string): Promise<AccountPortfolioClient> {
    // Connect to the Tendermint RPC endpoint
    const tendermintClient = await Tendermint34Client.connect(rpcEndpoint);
    
    // Create QueryClient that will be used by all module clients
    const queryClient = new QueryClient(tendermintClient);
    
    // Create the individual module clients
    const bankClient = new BankQueryClient(tendermintClient, queryClient);
    const stakingClient = new StakingQueryClient(tendermintClient, queryClient);
    const distributionClient = new DistributionQueryClient(tendermintClient, queryClient);
    
    // Return the composite client instance
    return new AccountPortfolioClient(
      tendermintClient,
      bankClient,
      stakingClient,
      distributionClient
    );
  }
  
  // Private constructor - use the static connect method to create instances
  private constructor(
    tendermintClient: Tendermint34Client,
    bankClient: BankQueryClient,
    stakingClient: StakingQueryClient,
    distributionClient: DistributionQueryClient
  ) {
    this.tendermintClient = tendermintClient;
    this.bankClient = bankClient;
    this.stakingClient = stakingClient;
    this.distributionClient = distributionClient;
  }
  
  // Get complete portfolio with liquid, staked, and reward balances
  async getFullPortfolio(address: string) {
    // Execute all queries in parallel for better performance
    const [
      balancesResponse,
      delegationsResponse,
      unbondingResponse,
      rewardsResponse
    ] = await Promise.all([
      this.bankClient.allBalances({ address }),
      this.stakingClient.delegatorDelegations({ delegatorAddr: address }),
      this.stakingClient.delegatorUnbondingDelegations({ delegatorAddr: address }),
      this.distributionClient.delegationTotalRewards({ delegatorAddress: address })
    ]);
    
    // Process liquid balances
    const liquidBalances = balancesResponse.balances.map(coin => ({
      denom: coin.denom,
      amount: coin.amount,
      displayAmount: this.formatAmount(coin.amount, coin.denom)
    }));
    
    // Calculate total liquid balance in uatom (for simplicity)
    const totalLiquid = liquidBalances.reduce(
      (sum, coin) => coin.denom === "uatom" ? sum + Number(coin.amount) : sum,
      0
    );
    
    // Process delegations (staked tokens)
    const delegations = delegationsResponse.delegationResponses.map(del => ({
      validatorAddress: del.delegation.validatorAddress,
      amount: del.balance.amount,
      denom: del.balance.denom,
      displayAmount: this.formatAmount(del.balance.amount, del.balance.denom)
    }));
    
    // Calculate total staked
    const totalStaked = delegations.reduce(
      (sum, del) => del.denom === "uatom" ? sum + Number(del.amount) : sum,
      0
    );
    
    // Process unbonding delegations
    const unbonding = unbondingResponse.unbondingResponses.map(unbond => {
      // Sum up all unbonding entries
      const totalAmount = unbond.entries.reduce(
        (sum, entry) => sum + Number(entry.balance),
        0
      );
      
      return {
        validatorAddress: unbond.validatorAddress,
        entries: unbond.entries.length,
        totalAmount: totalAmount.toString(),
        displayAmount: this.formatAmount(totalAmount.toString(), "uatom")
      };
    });
    
    // Calculate total unbonding
    const totalUnbonding = unbondingResponse.unbondingResponses.reduce(
      (sum, unbond) => sum + unbond.entries.reduce(
        (entrySum, entry) => entrySum + Number(entry.balance),
        0
      ),
      0
    );
    
    // Process rewards
    const rewards = rewardsResponse.rewards.map(reward => ({
      validatorAddress: reward.validatorAddress,
      rewards: reward.reward.map(r => ({
        denom: r.denom,
        amount: r.amount,
        displayAmount: this.formatAmount(r.amount, r.denom)
      }))
    }));
    
    // Calculate total rewards (simplifying to just uatom rewards)
    const totalRewards = rewardsResponse.total.reduce(
      (sum, reward) => reward.denom === "uatom" ? sum + Number(reward.amount) : sum,
      0
    );
    
    // Return comprehensive portfolio data
    return {
      address,
      liquid: {
        balances: liquidBalances,
        total: totalLiquid,
        displayTotal: this.formatAmount(totalLiquid.toString(), "uatom")
      },
      staked: {
        delegations,
        total: totalStaked,
        displayTotal: this.formatAmount(totalStaked.toString(), "uatom")
      },
      unbonding: {
        entries: unbonding,
        total: totalUnbonding,
        displayTotal: this.formatAmount(totalUnbonding.toString(), "uatom")
      },
      rewards: {
        details: rewards,
        total: totalRewards,
        displayTotal: this.formatAmount(totalRewards.toFixed(0), "uatom")
      },
      // Calculate combined portfolio value
      netWorth: {
        total: totalLiquid + totalStaked + totalUnbonding + Math.floor(totalRewards),
        displayTotal: this.formatAmount(
          (totalLiquid + totalStaked + totalUnbonding + Math.floor(totalRewards)).toString(),
          "uatom"
        )
      }
    };
  }
  
  // Helper to format token amounts for display
  private formatAmount(amount: string, denom: string): string {
    // Handle different denominations
    if (denom === "uatom") {
      const atoms = Number(amount) / 1_000_000;
      return `${atoms.toLocaleString()} ATOM`;
    }
    
    // For simplicity, just return the raw values for other denoms
    return `${amount} ${denom}`;
  }
  
  // Clean up resources
  disconnect(): void {
    this.tendermintClient.disconnect();
  }
}

// Usage example
async function useCompositeClient() {
  let client: AccountPortfolioClient | null = null;
  
  try {
    // Create the composite client
    client = await AccountPortfolioClient.connect("https://rpc.cosmos.network");
    
    // Use the client to get portfolio information
    const address = "cosmos1..."; // Replace with a real address
    const portfolio = await client.getFullPortfolio(address);
    
    // Display the portfolio information
    console.log(`=== Portfolio for ${address} ===`);
    console.log(`\nLiquid balance: ${portfolio.liquid.displayTotal}`);
    console.log(`Staked balance: ${portfolio.staked.displayTotal}`);
    console.log(`Unbonding: ${portfolio.unbonding.displayTotal}`);
    console.log(`Pending rewards: ${portfolio.rewards.displayTotal}`);
    console.log(`\nTotal net worth: ${portfolio.netWorth.displayTotal}`);
    
    // Show delegations
    if (portfolio.staked.delegations.length > 0) {
      console.log("\nDelegations:");
      portfolio.staked.delegations.forEach(del => {
        console.log(`- Validator ${del.validatorAddress}: ${del.displayAmount}`);
      });
    }
    
    // Show liquid balances
    if (portfolio.liquid.balances.length > 0) {
      console.log("\nLiquid balances:");
      portfolio.liquid.balances.forEach(balance => {
        console.log(`- ${balance.displayAmount}`);
      });
    }
  } catch (error) {
    console.error("Error:", error.message);
  } finally {
    // Always clean up resources
    if (client) {
      client.disconnect();
    }
  }
}

useCompositeClient();
```

## Working with Tendermint Subscriptions

One of the powerful features of the Tendermint RPC client is the ability to subscribe to real-time events. Let's see how to combine this with our client classes:

```typescript
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";
import { createRPCQueryClientClasses } from "./codegen/client-classes";

async function monitorBlocksAndValidators() {
  let tmClient: Tendermint34Client | null = null;
  
  try {
    console.log("Connecting to Tendermint WebSocket...");
    tmClient = await Tendermint34Client.connect("wss://rpc.cosmos.network/websocket");
    console.log("Connected!");
    
    // Create RPC Client Classes using our existing Tendermint client
    const clientClasses = createRPCQueryClientClasses({
      rpcEndpoint: tmClient
    });
    
    // Get initial validator set
    const { validators: initialValidators } = await clientClasses.cosmos.staking.v1beta1.validators({
      status: "BOND_STATUS_BONDED"
    });
    
    console.log(`Initial validator count: ${initialValidators.length}`);
    
    // Create a validator map for quick lookups
    const validatorMap = new Map();
    initialValidators.forEach(validator => {
      validatorMap.set(validator.operatorAddress, {
        moniker: validator.description.moniker,
        votingPower: validator.tokens
      });
    });
    
    // Subscribe to new blocks
    console.log("Subscribing to new blocks...");
    const subscription = tmClient.subscribeNewBlock().subscribe({
      next: async (block) => {
        const height = block.header.height;
        const time = new Date(block.header.time).toLocaleString();
        const txCount = block.txs.length;
        
        console.log(`\nNew block #${height} at ${time}`);
        console.log(`Contains ${txCount} transactions`);
        
        // If this is a significant block (every 100 blocks), query validators again
        if (parseInt(height) % 100 === 0) {
          try {
            console.log("Checking for validator changes...");
            
            const { validators: currentValidators } = await clientClasses.cosmos.staking.v1beta1.validators({
              status: "BOND_STATUS_BONDED"
            });
            
            // Check for changes in the validator set
            let changes = false;
            
            // Check for new validators
            currentValidators.forEach(validator => {
              if (!validatorMap.has(validator.operatorAddress)) {
                console.log(`New validator: ${validator.description.moniker}`);
                changes = true;
                
                // Update our map
                validatorMap.set(validator.operatorAddress, {
                  moniker: validator.description.moniker,
                  votingPower: validator.tokens
                });
              } else {
                // Check for voting power changes
                const oldPower = validatorMap.get(validator.operatorAddress).votingPower;
                if (oldPower !== validator.tokens) {
                  const oldPowerNum = parseInt(oldPower);
                  const newPowerNum = parseInt(validator.tokens);
                  const percentChange = ((newPowerNum - oldPowerNum) / oldPowerNum * 100).toFixed(2);
                  
                  console.log(`Validator ${validator.description.moniker} voting power changed by ${percentChange}%`);
                  changes = true;
                  
                  // Update our map
                  validatorMap.set(validator.operatorAddress, {
                    moniker: validator.description.moniker,
                    votingPower: validator.tokens
                  });
                }
              }
            });
            
            // Check for removed validators
            const currentValidatorAddresses = new Set(
              currentValidators.map(v => v.operatorAddress)
            );
            
            validatorMap.forEach((value, address) => {
              if (!currentValidatorAddresses.has(address)) {
                console.log(`Validator removed: ${value.moniker}`);
                changes = true;
                
                // Remove from our map
                validatorMap.delete(address);
              }
            });
            
            if (!changes) {
              console.log("No validator changes detected");
            }
          } catch (error) {
            console.error("Error checking validators:", error.message);
          }
        }
      },
      error: (err) => {
        console.error("Subscription error:", err.message);
      }
    });
    
    // Keep the subscription active for demonstration
    console.log("Monitoring blocks. Press Ctrl+C to exit...");
    
    // For demonstration purposes, keep the process running
    await new Promise(resolve => setTimeout(resolve, 300000)); // 5 minutes
    
    // Clean up
    subscription.unsubscribe();
    
  } catch (error) {
    console.error("Error:", error.message);
  } finally {
    // Always clean up resources
    if (tmClient) {
      console.log("Disconnecting...");
      tmClient.disconnect();
    }
  }
}

monitorBlocksAndValidators();
```

## Implementing Pagination Helpers

Many queries return large result sets that require pagination. Let's create a client with pagination helpers:

```typescript
import { StakingQueryClient } from "./codegen/cosmos/staking/v1beta1/query.rpc.Query";
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";
import { QueryClient } from "@cosmjs/stargate";

class PaginatedStakingClient extends StakingQueryClient {
  // Get all validators with automatic pagination
  async getAllValidators(status = "") {
    let allValidators = [];
    let nextKey = null;
    let pageCount = 0;
    
    console.log("Fetching all validators with pagination...");
    
    do {
      pageCount++;
      
      // Prepare request with pagination
      const request: any = {};
      
      // Add status filter if provided
      if (status) {
        request.status = status;
      }
      
      // Add pagination parameters
      request.pagination = nextKey 
        ? { key: nextKey, limit: "100" } 
        : { limit: "100" };
      
      // Query this page of validators
      const response = await this.validators(request);
      
      // Process this page
      const validators = response.validators;
      console.log(`Page ${pageCount}: Retrieved ${validators.length} validators`);
      
      // Add to our collection
      allValidators = [...allValidators, ...validators];
      
      // Get key for next page (if any)
      nextKey = response.pagination?.nextKey || null;
      
    } while (nextKey && nextKey.length > 0);
    
    console.log(`Completed pagination. Retrieved ${allValidators.length} validators in total`);
    return allValidators;
  }
  
  // Get all delegations for a delegator with automatic pagination
  async getAllDelegatorDelegations(delegatorAddr) {
    let allDelegations = [];
    let nextKey = null;
    let pageCount = 0;
    
    console.log(`Fetching all delegations for ${delegatorAddr}...`);
    
    do {
      pageCount++;
      
      // Prepare request with pagination
      const request = {
        delegatorAddr,
        pagination: nextKey 
          ? { key: nextKey, limit: "100" } 
          : { limit: "100" }
      };
      
      // Query this page of delegations
      const response = await this.delegatorDelegations(request);
      
      // Process this page
      const delegations = response.delegationResponses;
      console.log(`Page ${pageCount}: Retrieved ${delegations.length} delegations`);
      
      // Add to our collection
      allDelegations = [...allDelegations, ...delegations];
      
      // Get key for next page (if any)
      nextKey = response.pagination?.nextKey || null;
      
    } while (nextKey && nextKey.length > 0);
    
    console.log(`Completed pagination. Retrieved ${allDelegations.length} delegations in total`);
    return allDelegations;
  }
}

// Usage example
async function usePaginationHelpers() {
  let tmClient: Tendermint34Client | null = null;
  
  try {
    // Connect to the blockchain
    tmClient = await Tendermint34Client.connect("https://rpc.cosmos.network");
    const queryClient = new QueryClient(tmClient);
    
    // Create our enhanced client
    const stakingClient = new PaginatedStakingClient(tmClient, queryClient);
    
    // Get all active validators
    console.log("Getting all bonded validators...");
    const bondedValidators = await stakingClient.getAllValidators("BOND_STATUS_BONDED");
    console.log(`Found ${bondedValidators.length} active validators`);
    
    // Get all validators (including unbonded and unbonding)
    console.log("\nGetting all validators...");
    const allValidators = await stakingClient.getAllValidators();
    console.log(`Found ${allValidators.length} total validators`);
    
    // Analyze validator statuses
    const statusCounts = {
      "BOND_STATUS_BONDED": 0,
      "BOND_STATUS_UNBONDING": 0,
      "BOND_STATUS_UNBONDED": 0,
      "BOND_STATUS_UNSPECIFIED": 0
    };
    
    allValidators.forEach(validator => {
      statusCounts[validator.status]++;
    });
    
    console.log("\nValidator status breakdown:");
    console.log(`- Bonded: ${statusCounts["BOND_STATUS_BONDED"]}`);
    console.log(`- Unbonding: ${statusCounts["BOND_STATUS_UNBONDING"]}`);
    console.log(`- Unbonded: ${statusCounts["BOND_STATUS_UNBONDED"]}`);
    console.log(`- Unspecified: ${statusCounts["BOND_STATUS_UNSPECIFIED"]}`);
    
    // Now get all delegations for an address
    const address = "cosmos1..."; // Replace with a real address
    console.log(`\nGetting all delegations for ${address}...`);
    
    const delegations = await stakingClient.getAllDelegatorDelegations(address);
    console.log(`Found ${delegations.length} delegations`);
    
    if (delegations.length > 0) {
      console.log("\nDelegation summary:");
      let totalStaked = 0;
      
      delegations.forEach(del => {
        const amount = parseInt(del.balance.amount);
        totalStaked += amount;
        
        console.log(`- ${del.delegation.validatorAddress}: ${amount / 1_000_000} ATOM`);
      });
      
      console.log(`\nTotal staked: ${totalStaked / 1_000_000} ATOM`);
    }
    
  } catch (error) {
    console.error("Error:", error.message);
  } finally {
    // Always clean up
    if (tmClient) {
      tmClient.disconnect();
    }
  }
}

usePaginationHelpers();
```

## Conclusion

In this tutorial, you've learned how to:

1. Enable and generate RPC Client Classes with Telescope
2. Create and use basic RPC Client Classes
3. Understand the different client types (Tendermint, gRPC-web, gRPC-gateway)
4. Extend client classes with custom functionality
5. Create composite clients that combine multiple module clients
6. Work with Tendermint subscriptions for real-time updates
7. Implement pagination helpers for large data sets

RPC Client Classes provide a powerful object-oriented approach to interacting with Cosmos SDK blockchains. By extending and combining these classes, you can create reusable, maintainable code that fits your application's specific needs.

In the next tutorial, we'll explore [Instant RPC Methods](./instant-rpc-methods.md) for simplified access to common blockchain operations. 