# Working with Types

In this tutorial, we'll dive into the TypeScript types generated by Telescope and learn how to use them effectively in your Cosmos SDK applications. Understanding these types is crucial for building type-safe applications that interact with the blockchain.

## Understanding Generated Types

When you run Telescope against Protocol Buffer definitions, it generates several TypeScript files containing types, interfaces, and helper functions. Let's explore the main categories of generated types and understand their purpose.

### Message Types

The most common types you'll work with are message types, which represent the data structures defined in Protocol Buffers. For example, a simple bank transfer message:

```typescript
// In the original .proto file
message MsgSend {
  string from_address = 1;
  string to_address = 2;
  repeated Coin amount = 3;
}
```

Telescope generates a TypeScript interface and helper functions:

```typescript
// Generated TypeScript
export interface MsgSend {
  fromAddress: string;
  toAddress: string;
  amount: Coin[];
}

export const MsgSend = {
  // Serializes a MsgSend object to binary format
  encode(message: MsgSend, writer: Writer = Writer.create()): Writer {
    // implementation details...
  },
  
  // Deserializes binary data into a MsgSend object
  decode(input: Reader | Uint8Array, length?: number): MsgSend {
    // implementation details...
  },
  
  // Converts a JSON object to a MsgSend
  fromJSON(object: any): MsgSend {
    // implementation details...
  },
  
  // Converts a MsgSend to a JSON object
  toJSON(message: MsgSend): unknown {
    // implementation details...
  },
  
  // Creates a MsgSend from a partial object
  fromPartial(object: DeepPartial<MsgSend>): MsgSend {
    // implementation details...
  }
}
```

### Practical Example: Creating and Using a Message

Let's see how to use these generated types in practice:

```typescript
import { MsgSend } from "./cosmos/bank/v1beta1/tx";

// Create a message using the fromPartial helper
const transferMsg = MsgSend.fromPartial({
  fromAddress: "cosmos1sender...",
  toAddress: "cosmos1recipient...",
  amount: [
    { denom: "uatom", amount: "1000000" } // 1 ATOM (in microatoms)
  ]
});

// You can also create the message directly
const anotherMsg: MsgSend = {
  fromAddress: "cosmos1sender...",
  toAddress: "cosmos1recipient...",
  amount: [
    { denom: "uatom", amount: "1000000" }
  ]
};

// Convert to JSON for debugging or other purposes
const jsonMsg = MsgSend.toJSON(transferMsg);
console.log(jsonMsg);

// Later, you can recreate the message from JSON
const recreatedMsg = MsgSend.fromJSON(jsonMsg);
```

The `fromPartial` method is particularly useful as it allows you to create a message without providing all the fields, filling in defaults as appropriate.

## Working with Any Types

The Protocol Buffers `Any` type is a special container that can hold any message type. This is useful for scenarios where you need to handle multiple message types dynamically, such as in transaction processing.

```typescript
import { Any } from "./google/protobuf/any";
import { MsgSend } from "./cosmos/bank/v1beta1/tx";
import { MsgDelegate } from "./cosmos/staking/v1beta1/tx";

// Create your message
const sendMsg = MsgSend.fromPartial({
  fromAddress: "cosmos1...",
  toAddress: "cosmos1...",
  amount: [{ denom: "uatom", amount: "1000000" }]
});

// Pack it into an Any
const packedMsg = Any.pack(sendMsg, "/cosmos.bank.v1beta1.MsgSend");

// Now you can include it in another message that expects Any types
// For example, in a transaction that can contain different message types

// Later, you can unpack it when you know what type it contains
if (packedMsg.typeUrl === "/cosmos.bank.v1beta1.MsgSend") {
  const unpackedSendMsg = packedMsg.unpack(MsgSend);
  console.log(unpackedSendMsg.toAddress);
} else if (packedMsg.typeUrl === "/cosmos.staking.v1beta1.MsgDelegate") {
  const unpackedDelegateMsg = packedMsg.unpack(MsgDelegate);
  // Work with delegate message
}
```

### Using the Global Decoder Registry

For more complex applications, Telescope can generate a global decoder registry to handle Any types more dynamically:

```typescript
import { Registry } from "./registry";
import { Any } from "./google/protobuf/any";

// Create a registry with all your types
const registry = new Registry();

// Any message can be unpacked using the registry
function processAnyMessage(anyMsg: Any) {
  const unpacked = registry.unpack(anyMsg);
  if (unpacked) {
    // Handle the message based on its type
    if ("toAddress" in unpacked) {
      // This is likely a MsgSend
      console.log(`Sending to: ${unpacked.toAddress}`);
    } else if ("validatorAddress" in unpacked) {
      // This is likely a MsgDelegate
      console.log(`Delegating to: ${unpacked.validatorAddress}`);
    }
  }
}
```

## Amino Types for Legacy Compatibility

If you're working with older wallets (like Keplr) or systems that use the Amino encoding format, you'll need to use the Amino types generated by Telescope.

```typescript
import { MsgSend } from "./cosmos/bank/v1beta1/tx";
import { AminoTypes } from "@cosmjs/stargate";
import { aminoConverters } from "./amino/cosmos.bank.v1beta1.tx";

// Create your message
const sendMsg = MsgSend.fromPartial({
  fromAddress: "cosmos1...",
  toAddress: "cosmos1...",
  amount: [{ denom: "uatom", amount: "1000000" }]
});

// Set up amino types with the generated converters
const aminoTypes = new AminoTypes(aminoConverters);

// Convert to amino format (for legacy wallets)
const aminoMsg = aminoTypes.toAmino({
  typeUrl: "/cosmos.bank.v1beta1.MsgSend",
  value: sendMsg
});

console.log(aminoMsg);
// Output: 
// {
//   type: "cosmos-sdk/MsgSend",
//   value: {
//     from_address: "cosmos1...",
//     to_address: "cosmos1...",
//     amount: [{ denom: "uatom", amount: "1000000" }]
//   }
// }

// Later, convert back from amino format
const protoMsg = aminoTypes.fromAmino(aminoMsg);
```

## Special Types and Their Handling

Telescope provides special handling for certain common types:

### Timestamps

```typescript
import { Timestamp } from "./google/protobuf/timestamp";

// Create a timestamp from a Date
const now = new Date();
const timestamp = Timestamp.fromDate(now);

// Or manually
const manualTimestamp = Timestamp.fromPartial({
  seconds: BigInt(Math.floor(now.getTime() / 1000)),
  nanos: (now.getTime() % 1000) * 1000000
});

// Convert back to a Date
const dateFromTimestamp = timestamp.toDate();
```

### Coins

Cosmos SDK uses a special `Coin` type for representing tokens:

```typescript
import { Coin } from "./cosmos/base/v1beta1/coin";

// Create a coin representing 5 ATOM
const atomCoin: Coin = {
  denom: "uatom",
  amount: "5000000" // 5 ATOM in microatoms (uatom)
};

// Helper function to format coins for display
function formatCoin(coin: Coin): string {
  const amount = parseInt(coin.amount);
  if (coin.denom.startsWith("u")) {
    // Convert micro units to whole units for display
    return `${amount / 1000000} ${coin.denom.substring(1).toUpperCase()}`;
  }
  return `${amount} ${coin.denom.toUpperCase()}`;
}

console.log(formatCoin(atomCoin)); // "5 ATOM"
```

## Client Types and How to Use Them

Telescope generates different client types to interact with the blockchain:

### Query Clients

Query clients are used to query the blockchain state:

```typescript
import { createRPCQueryClient } from "./rpc.query";

// Create a query client connected to your node
const client = await createRPCQueryClient({ rpcEndpoint: "https://rpc.cosmos.network" });

// Query account balances
const balances = await client.cosmos.bank.v1beta1.allBalances({
  address: "cosmos1..."
});

console.log("Balances:", balances.balances);

// Query validator information
const validator = await client.cosmos.staking.v1beta1.validator({
  validatorAddr: "cosmosvaloper1..."
});

console.log("Validator:", validator.validator);
```

### Transaction Clients

Transaction clients are used to create and send transactions:

```typescript
import { MsgSend } from "./cosmos/bank/v1beta1/tx";
import { createTxClient } from "./tx";
import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";

// Create a wallet
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(
  "your mnemonic phrase here",
  { prefix: "cosmos" }
);
const [account] = await wallet.getAccounts();

// Create a transaction client
const txClient = await createTxClient({
  signer: wallet,
  rpcEndpoint: "https://rpc.cosmos.network"
});

// Create and send a transaction
const result = await txClient.signAndBroadcast(
  account.address,
  [
    MsgSend.fromPartial({
      fromAddress: account.address,
      toAddress: "cosmos1recipient...",
      amount: [{ denom: "uatom", amount: "1000000" }]
    })
  ],
  {
    gas: "200000",
    amount: [{ denom: "uatom", amount: "5000" }]
  }
);

console.log("Transaction result:", result);
```

## Type Safety Tips and Best Practices

1. **Use `fromPartial` for creating messages**
   
   The `fromPartial` method provides a safer way to create messages by filling in default values for omitted fields:
   
   ```typescript
   // Good: Uses fromPartial
   const msg = MsgSend.fromPartial({ 
     fromAddress: "cosmos1...",
     toAddress: "cosmos1..."
     // amount will be initialized to an empty array
   });
   
   // Less safe: Direct initialization might leave required fields undefined
   const directMsg: MsgSend = { 
     fromAddress: "cosmos1...",
     toAddress: "cosmos1..."
     // Oops, forgot amount!
   };
   ```

2. **Leverage TypeScript's type checking**
   
   Let the TypeScript compiler help you catch errors:
   
   ```typescript
   // TypeScript will flag this error
   const msg = MsgSend.fromPartial({
     fromAddress: "cosmos1...",
     toAddress: "cosmos1...",
     amount: [{ denom: 123, amount: "1000" }] // Error: denom should be a string!
   });
   ```

3. **Handle optional fields appropriately**
   
   ```typescript
   function processProposal(proposal: any) {
     // Check if optional fields exist before using them
     if (proposal.content && proposal.content.title) {
       console.log("Proposal title:", proposal.content.title);
     }
     
     // Or use optional chaining
     console.log("Proposal title:", proposal.content?.title);
   }
   ```

4. **Use typed arrays for repeated fields**
   
   ```typescript
   // Create a properly typed array of coins
   const amounts: Coin[] = [
     { denom: "uatom", amount: "1000000" },
     { denom: "usomm", amount: "5000000" }
   ];
   
   // Now you can use array methods with proper typing
   const totalAmount = amounts
     .filter(coin => coin.denom === "uatom")
     .reduce((sum, coin) => sum + parseInt(coin.amount), 0);
   ```

## Summary

In this tutorial, we've explored the TypeScript types generated by Telescope and how to use them effectively in your applications. You've learned:

- How to work with message types and their helper functions
- How to handle dynamic types with `Any`
- How to use Amino types for legacy compatibility
- How to work with special types like timestamps and coins
- How to use query and transaction clients to interact with the blockchain
- Best practices for maintaining type safety

By leveraging these generated types, you can build more robust and type-safe applications that interact with Cosmos-based blockchains, with much less manual type definition and manipulation.

Next, check out the [Composing Messages tutorial](./composing-messages.md) to learn how to create and send complex blockchain transactions. 